### ISSUE TITLE
[Feature]: enhance mapper to produce realistic test data

### ISSUE THREAD

**Issue by aphethean1** [meltano/sdk#1009]
### Feature scope

Other

### Description

As a user, I need to move data from a production database to a test database keeping realistic looking values for names, addresses, and so on, but not share actual personal information.

## proposal

Add a dependency on 'faker' library
https://github.com/joke2k/faker/blob/master/setup.py#L73-L77

Enable mapper configuration similar to md5 to mask values during a run from tap to target.

## benefits and use cases

As of today, it is possible to use a hashing function like md5() but with this feature, we will have data that "looks like" real data - especially good for test environments!

## links

https://app.slack.com/client/TFG99TU9K/C013EKWA2Q1/thread/C013EKWA2Q1-1664297456.961009

**Comment by edgarrmondragon** [comment]
Still open to support this. Faker is a pure-python dependency with an MIT license. We probably want to give users the option to configure [locale](https://faker.readthedocs.io/en/master/#localization) and [seed](https://faker.readthedocs.io/en/master/#seeding-the-generator).
