### ISSUE TITLE
bug: New `BATCH` functionality fails if output folder is missing

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1014]
### Singer SDK Version

0.11.1

### Python Version

3.10

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Linux

### Description

Currently, if the folder specified as `storage.root` in [batch_config](https://sdk.meltano.com/en/latest/batch.html#batch-configuration) does not exist, the tap will run and fail on writing the first batch. Preferably we could create this with `Path.mkdir(parents=True, exists_ok=True)` but at a minimum we should check it exists before fetching records in order to 'fail fast'.

Possible solutions:
1. Create the root if not exists _before_ fetching any records, and fail if creation fails.
2. Check if root exists before fetching any records and fail if it doesn't (i.e. do not create).

### Code

```python
https://github.com/meltano/squared/actions/runs/3152108087/jobs/5126999218#step:8:149
```

**Comment by edgarrmondragon** [comment]
This might be as simple as using the keyword argument `create=True` when calling https://github.com/meltano/sdk/blob/721b6f9d444dd86c1a33ef98df8e2a4a3c035618/singer_sdk/helpers/_batch.py#L157-L169

All the keyword arguments are passed to https://docs.pyfilesystem.org/en/latest/reference/opener.html#fs.opener.registry.Registry.open_fs
