### ISSUE TITLE
[Feature]: speed up discovery, just discover selected tables

### ISSUE THREAD

**Issue by s7clarke10** [meltano/sdk#1048]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

I'm not sure if this is a capability of the SDK for database taps or not.

We were finding that the Discovery of Tables running in an ephemeral container deployment where you always have to discover not satisfactory when you have a large number of tables in the source system. On a particular database, this was taking 2-5 minutes due to the slowness of the Oracle Data Dictionary and the large number of tables.

We decided that we would add a feature to just discover selected tables i.e., tables set in the config or in the MELTANO __SELECT environment variable. If that config item was set, then the discovery was limited to just the selected tables. With that in place discover went from 2-5 minutes to a few seconds.

This was the particular change that we placed in pipelinewise-tap-oracle to support this feature.

https://github.com/s7clarke10/pipelinewise-tap-oracle/commit/d348c4e5f8d0ecac53e2cdb57585760df7fe230a
https://github.com/s7clarke10/pipelinewise-tap-oracle/commit/d545a7d37083bb505b91037e686fea32209c5dbd

Just sharing this idea as I believe it is a helpful feature.

**Comment by kgpayne** [comment]
+1 Ran into slow discovery with Snowflake too, which would benefit from this feature.

**Comment by edgarrmondragon** [comment]
Duplicate of https://github.com/meltano/sdk/issues/1234
