### ISSUE TITLE
[Bug]: Meltano error print does not respect JSON logging settings

### ISSUE THREAD

**Issue by spacecowboy** [meltano/sdk#1069]
### Singer SDK Version

0.11.1

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Linux

### Description

We are running `meltano run ...` in the cloud and are using JSON-formatted logs via  `logging.config`.

Latest version of the SDK have started to print a message when something goes wrong and this does not respect the JSON output, meaning it gets split across several log entries in StackDriver, interleaved with other messages. A bit like this

```
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
{}
{}
time=2022-10-13 09:33:49 name=singer level=INFO message=METRIC: {"type": "counter", "metric": "record_count", "value": 58075, "tags": {}}

```

## Expected output

If JSON logging if configured, then all output should respect that.

As a side note, this output is not very helpful and would be nice if it were removed entirely.

**Comment by tayloramurphy** [comment]
@spacecowboy thanks for the issue. @edgarrmondragon thoughts on what's causing this?

**Comment by edgarrmondragon** [comment]
@tayloramurphy yeah, this is coming from Meltano actually (https://github.com/meltano/meltano/pull/6748), not the SDK.

We should probably check if the terminal is interactive to display the troubleshooting message, and log an error in any case.

**Comment by tayloramurphy** [comment]
@edgarrmondragon will you make an issue in the meltano project and crosslink?

**Comment by edgarrmondragon** [comment]
@tayloramurphy done: https://github.com/meltano/meltano/issues/6883

**Comment by edgarrmondragon** [comment]
@spacecowboy I assume you're referring to the message

> Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to join our friendly Slack community.

That's coming from Meltano and not the SDK, so I'm curious: you were probably seeing other non-JSON lines, because we only changed the message contents: https://github.com/meltano/meltano/commit/e4d698495e50ee9d0a81d4885dced8f79f519982?diff=unified#diff-db51eaa4dbd480b0dc4896b3c9c85450b2308b6dfa51b1f45d0f6b143e61f64eR104

Perhaps it's only an issue now because it's multiline? (I'm trying to think if this could be a larger problem we need to watch out for=

**Comment by spacecowboy** [comment]
> @spacecowboy I assume you're referring to the message
> 
> > Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to join our friendly Slack community.
> 
> That's coming from Meltano and not the SDK, so I'm curious: you were probably seeing other non-JSON lines, because we only changed the message contents: [meltano/meltano@e4d6984?diff=unified#diff-db51eaa4dbd480b0dc4896b3c9c85450b2308b6dfa51b1f45d0f6b143e61f64eR104](https://github.com/meltano/meltano/commit/e4d698495e50ee9d0a81d4885dced8f79f519982?diff=unified#diff-db51eaa4dbd480b0dc4896b3c9c85450b2308b6dfa51b1f45d0f6b143e61f64eR104)
> 
> Perhaps it's only an issue now because it's multiline? (I'm trying to think if this could be a larger problem we need to watch out for=

Ah yes you're right. It's meltano and not the SDK. Thanks for copying the issue.

Yes, the issue that it's multi line.

And because it's only printed when there is an error, it gets interleaved with the logging which I'm trying to process to find the real issue.
