### ISSUE TITLE
[Feature]: Show contents of JSON file when loading fails

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1081]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

When failing to load a catalog file, the singer SDK doesn't offer too many details as to why the error occurred and users are left with errors like `Expecting value: line 1 column 1 (char 0)`, which are rather non-informative.

Perhaps we should handle the [JSONDecodeError](https://docs.python.org/3/library/json.html#json.JSONDecodeError) exception raised by `json.loads` in 
https://github.com/meltano/sdk/blob/bc3ff0825446ddc9e63ebff2c4ac5ecf7c046aa2/singer_sdk/helpers/_util.py#L22 to display where the error occurred and what's the offending content.

See https://github.com/meltano/meltano/issues/6878

**Comment by visch** [comment]
+100 I've hit this too man times to count!

**Comment by edgarrmondragon** [comment]
The detailed error treatment should probably be only applied to catalog and state files, and not config.

**Comment by visch** [comment]
> The detailed error treatment should probably be only applied to catalog and state files, and not config.

Ideally it'd say "config.json parsing issue" to see config.json run with --log-level=debug or something so that you can still debug it 🤷

**Comment by edgarrmondragon** [comment]
Still relevant
