### ISSUE TITLE
refactor: Move `SQLConnector` into a separate module, for use by both `SQLStream` and `SQLSink`

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1090]
Currently the `SQLConnector` class is in `stream` module in the same file as `SQLStream`, however it is also needed by `SQLSink` from the `sink` module. Moving the connector into a `sql` module would make it easier to work on sinks, and also provide a place for other shared, SQL-related code.

**Comment by BuzzCutNorman** [comment]
What about having a `SQLConnector` class and a `SQLConnectorSink(SQLConnector)` where all the sink specific functions could be housed.  Examples would be `create_schema`, `prepare_column`, `_adapt_column_type`, `merge_sql_types`, `rename_column`.
