### ISSUE TITLE
bug: replication key should  not be required for log based method

### ISSUE THREAD

**Issue by lidong-zhao** [meltano/sdk#1121]
### Singer SDK Version

0.13.0

### Python Version

3.10

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Windows

### Description

replication key should  not be required for log based method. It throws exception if I don't specify replication key and the replication method is log based. Can we remove Current implementation REPLICATION_LOG_BASED from line 712 in /streams/core.py file? 

### Code

```python
https://github.com/meltano/sdk/blob/main/singer_sdk/streams/core.py#L712
```

**Comment by aaronsteers** [comment]
@lidong-zhao - Thanks for raising. Do you mind providing your repo link (if public)?

We don't have many real-world examples of LOG_BASED on the SDK, so would be helpful to see your implementation path as we consider the needed updates on the SDK side.

cc @edgarrmondragon

**Comment by lidong-zhao** [comment]
Our source database is SQL Server, the idea is that in the overridden get-records method, build a query based on CHANGETABLE to get incremental change since last sync.

**Comment by edgarrmondragon** [comment]
@aaronsteers what's the use for expected use case for a user-defined replication key in log-based? If not, then the default implementation should probably check it only for incremental.

**Comment by aaronsteers** [comment]
> @aaronsteers what's expected use case for a user-defined replication key in log-based? If not common, then the default implementation should probably check it only for incremental.

The original intention at the time was that `replication_key` would be toggled to the log-based key when in LOG_BASED replication mode.

Based on newer plans and discussions, though, we're leaning towards keeping both keys tracked separately, which would diverge from those original intentions.

This newer proposal suggests a new and distinct "log_based_replication_key":

- #1012

**Comment by aaronsteers** [comment]
So, to the core question:

Yes, I'm totally fine with the suggested change here. 👍

**Comment by aaronsteers** [comment]
I created this PR which should resolve the issue:

- #1126 

@lidong-zhao - Thanks for raising this. There are several folks working on SQL-based targets as of now. If you are able to share code and your learnings from building the LOG_BASED implementation, I think this would be really valuable to others. In addition to sharing code here and/or contributing additional issues/PRs, can also chat with us in `[#singer-target-development](https://meltano.slack.com/archives/C01RKUVUG4S)` in our [Meltano Slack](meltano.com/slack) if you run into any other issues.

**Comment by lidong-zhao** [comment]
I am happy to open source it once it is ready, I also have to get approval from our legal team. But here is the idea:
 1. Enable change tracking in SQL Server database.
 2. Override get-records method, add a flag to state to indicate if the initial full table replication is done or not, if not, replicate full table, if done, join the table with change tracking function to get incremental change.
