### ISSUE TITLE
[Feature]: add target tests to `singer_sdk.testing`

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1122]
### Feature scope

Targets (data type handling, batching, SQL object generation, etc.)

### Description

Currently there are no standard target tests included with the Singer SDK. A good selection of example tests is available in [MeltanoLabs/target-sqlite](https://github.com/MeltanoLabs/target-sqlite/tree/master/tests) that are readily portable to the SDK.

**Comment by BuzzCutNorman** [comment]
What route were you thinking.  I have them these be part of the cookie cutter or more of a TODO that we need to add particulars to variables?

**Comment by aaronsteers** [comment]
Closed with

- https://github.com/meltano/sdk/pull/1171
