### ISSUE TITLE
bug(sql-targets): missing fields are not automatically tranformed into `null` values during insert/merge

### ISSUE THREAD

**Issue by radbrt** [meltano/sdk#1134]
Fields can be present in the schema but not in the record, and this may create challenges when writing to a target.

I propose we add a generic method in the sdk to add these fields to the record, to target development easier.

**Comment by aaronsteers** [comment]
@radbrt - Thanks for raising this. I actually think this can be safely categorized as a bug and I've renamed to reflect this.

Also, I've added to the SQL Target milestone for tracking there..

**Comment by edgarrmondragon** [comment]
@radbrt @kgpayne instead of the target SDK filling in missing `NULL` values, wdyt about it using DDL to set the default value if the column is nullable, i.e.

```sql
create table users (
  id integer primary key,
  may_be_missing text default null
)
```

**Comment by kgpayne** [comment]
@edgarrmondragon I like that a lot 🙂 It would mean filling missing values with the `DEFAULT` keyword when passing parameters to our insert statement [here](https://github.com/meltano/sdk/blob/main/singer_sdk/sinks/sql.py#L306), and as its in the ANSI spec it should be widely supported 🤞 The alternative would be reading the default from the SCHEMA message and populating that, for systems that don't support default.

**Comment by radbrt** [comment]
@edgarrmondragon I had to test this to remember what the exact issue was, here is a failing insert from my testing:

```
2022-11-03T20:15:41.632679Z [info     ] [SQL: INSERT INTO liney_tmp    cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2022-11-03T20:15:41.632812Z [info     ] (ix, vv, _sdc_source_file, _sdc_source_lineno, _sdc_extra) cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2022-11-03T20:15:41.632944Z [info     ] VALUES (%(ix)s, %(vv)s, %(_sdc_source_file)s, %(_sdc_source_lineno)s, %(_sdc_extra)s)] cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2022-11-03T20:15:41.633087Z [info     ] [parameters: [{'ix': 'AA', 'vv': 121, '_sdc_source_file': './bk_liney_2.csv', '_sdc_source_lineno': 2},
```

As you might see, the insert statement includes the `_sdc_extra` field that usually isn't populated, but it isn't included in the actual data passed in. Because it is declared, I suspect the default using defaults, because the number of values passed in doesn't. match the number of volumns specified.

I'm going for @visch 's solution for now.

**Comment by edgarrmondragon** [comment]
@radbrt that makes sense. You're right and thinking a bit more about this, the SQL built-in default would require excluding the column in the `INSERT` statement, and thus still detecting if the record/batch is missing the field 👍

**Comment by kgpayne** [comment]
@edgarrmondragon FYI this was one of my next-up that would be good to hand over 🐣
