### ISSUE TITLE
Feature proposal: Add Parquet as a Batch encoding option

### ISSUE THREAD

**Issue by jamielxcarter** [meltano/sdk#1148]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Currently the only Batch encoding option is JSONL. This feature will add support for writing batch files as parquet.

**Comment by aaronsteers** [comment]
Hi, @jamielxcarter - thanks for logging this.

Just as a heads up, we currently have `pyarrow` as a dev dependency in the SDK, but this likely would propose adding as an `extra` or as a core dependency. We previously added special conditions for `pyarrow `inclusion because it did not yet support Python 3.11 - although it appears that is now resolved:

- https://github.com/apache/arrow/issues/14572

**Comment by jamielxcarter** [comment]
Thanks @aaronsteers. If it weren't already a dependency I think I would have used `fastparquet`, since it has a significantly smaller footprint: `fastparquet` 3.9M vs `pyarrow` 87M. I can add pyarrow as an extra just to be safe if that's what you prefer.

**Comment by aaronsteers** [comment]
@jamielxcarter - fastparquet actually sounds like a better choice, IMHO. 

The pyarrow dependent can be removed or refactored. As of now, pyarrow is only used for one of the samples (tap-parquet) and it's not actually leveraged as of now any of the main codebase.

**Comment by jamielxcarter** [comment]
> @jamielxcarter - `fastparquet` actually sounds like a better choice, IMHO. I haven't used it myself but I've heard quite a lot about it and the smaller footprint is very desirable.
> 
> The `pyarrow` dependent can be removed or refactored. To clarify my point above, as of now, `pyarrow` is only used for one of the samples (tap-parquet, as a dev/test sample for contributors) and it's not actually leveraged as of now any of the main codebase. As such, it isn't installed by default in taps and targets that use the SDK.
> 
> It sounds like `fastparquet` may be small enough to include it _by default_ in taps and targets, which is the ideal behavior, so that all taps and targets can support reading from and writing to parquet files, without additional work from the end user consuming the connector.

Hey @aaronsteers, I think the only issue with `fastparquet` is that it requires that we write using a `pandas` `dataframe`, where as `pyarrow` has a method specifically for writing from a list of python dictionaries. I still lean toward `fastparquet`, but it does mean importing `pandas.DataFrame`. Thoughts?

**Comment by VMois** [comment]
What do you think about adding support for arbitrary batch file format? Not only JSONL or Parquet, etc.

The use case, for example, is when I only want to copy files from tap to some staging area (CSV/Parquet files from an external S3 bucket to mine). This is currently not possible. If I specify a CSV file as encoding, my tap fails. The solution, for now, is to build a custom tap (no SDK) to handle messages.

**Comment by aaronsteers** [comment]
> What do you think about adding support for arbitrary batch file format? Not only JSONL or Parquet, etc.
> 
> The use case, for example, is when I only want to copy files from tap to some staging area (CSV/Parquet files from an external S3 bucket to mine). This is currently not possible. My tap fails if I specify a CSV file as encoding in the config.
> 
> https://github.com/meltano/sdk/blob/ad53dfa0d392042eb1078a037780e0d3cd8562e8/singer_sdk/helpers/_batch.py#L214

Did you have a specific implementation in mind? We don't have any specific preference to limit what formats should be supported, but for the dev effort, each file format generally requires a non-trivial amount of effort to generate and/or configure.

For example, Parquet is easy to configure but non-trivial to implement. CSV is trivial to implement but non-trivial to configure.

**Comment by VMois** [comment]
> Did you have a specific implementation in mind?

Nothing in mind. I think I have misunderstood how SDK exactly works. It does a lot of job for you to load/unpack files from S3/Local. For now, I have modified a non-SDK tap/target to work with a batch format I prefer (CSV, not compressed).

The idea for SDK can be the ability to define/extend formats and provide your methods to load/unpack data.

**Comment by aaronsteers** [comment]
@VMois - So happy to hear you've been able to build an implementation here! If you have time, I've love to hear your thoughts on our (very!) new spec proposal for CSV-backed batch message operations:

- #1584

**Comment by edgarrmondragon** [comment]
Still relevant

**Comment by BTheunissen** [comment]
I see a PR got opened for this item, once this gets released I'd like to add batch json/parquet support to my Target for Clickhouse :)
