### ISSUE TITLE
[Bug]: State should not be output until all records with the same state have been output

### ISSUE THREAD

**Issue by Jack-Burnett** [meltano/sdk#1165]
### Singer SDK Version

0.10.0

### Python Version

3.10

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Linux

### Description

The intention of outputting state messages part way through completion is that they could be used to resume progress from after that point on the next run of the tap.

However, I think this would breakdown if there were multiple records with the same state value (I think this would be a fairly common occurence for most taps).

Since if we output a state message for a given timestamp, then the tap terminates unexpectedly, then we resume, anything with the same state timestamp would then be skipped*.

I think the correct thing to do would most likely be changing from a strictly frequency based outputting of timestamps (https://github.com/meltano/sdk/blob/861dfc327aadfc4f57557b81a95063d7e6628b1c/singer_sdk/streams/core.py#L1088)
to instead outputting whenever the state is DIFFERENT from the state of the previous record (as long as the frequency had also been exceeded).

*Of course this depends how the tap is using the state but I feel like it is generally desirable to process all things strictly after the last state timestamp, not including it.

**Comment by edgarrmondragon** [comment]
This should've been addressed by https://github.com/meltano/sdk/pull/1708. Feel free to comment if not.
