### ISSUE TITLE
[Bug]: SQL connector forces column names to lower case but does not 

### ISSUE THREAD

**Issue by hsyyid** [meltano/sdk#1176]
### Singer SDK Version

0.13.0

### Python Version

3.10

### Bug scope

Targets (data type handling, batching, SQL object generation, etc.)

### Operating System

Linux

### Description

Pushing the following payload to `target-mssql` (https://github.com/radbrt/target-mssql/blob/main/target_mssql/connector.py):

```
{"type": "SCHEMA", "stream": "GeneralLedgerReport", "schema": {"type": ["object", "null"], "properties": {"Date": {"type": ["string", "null"]}, "CompanyName": {"type": ["string", "null"]}, "TransactionType": {"type": ["string", "null"]}, "Num": {"type": ["string", "null"]}, "Name": {"type": ["string", "null"]}, "Memo": {"type": ["string", "null"]}, "Split": {"type": ["string", "null"]}, "Class": {"type": ["string", "null"]}, "Department": {"type": ["string", "null"]}, "Amount": {"type": ["number", "null"]}, "Categories": {"type": ["string", "null"]}, "id": {"type": ["string", "null"]}, "entity_name": {"type": ["string", "null"]}, "entity_type": {"type": ["string", "null"]}}}, "key_properties": ["id"]}
{"type": "RECORD", "stream": "GeneralLedgerReport", "record": {"Date": "2022-01-01 00:00:00", "CompanyName": "Honeycomb Holdings Inc.", "TransactionType": "Invoice", "Num": "1100", "Name": "A1 NO_LASTNAME", "Split": "1100 Accounts Receivable", "Amount": 20.0, "Categories": "AcctRec : 1100 Accounts Receivable", "id": "1948988_0", "entity_name": "A1 NO_LASTNAME", "entity_type": "Customer"}}
```

As you can see the column names are capitalized. e.g. `Date` instead of `date`

The Meltano SDK forces all column names to be lowercase here: https://github.com/meltano/sdk/blob/main/singer_sdk/connectors/sql.py#L523

However, when checking if columns exist, it does not do the lookup with lowercase:
https://github.com/meltano/sdk/blob/main/singer_sdk/connectors/sql.py#L547

So in my case, it creates the table with column `date` and then checks if the column `Date` exists. It doesn't (due to the difference in case), so it tries to create again and fails because it tries to create a column `date` again. This fails the entire target.

Solution would be to force the `column_exists` function to also force column names to lowercase so targets don't deal with this weird behavior

**Comment by edgarrmondragon** [comment]
Thanks for reporting @hsyyid!

**Comment by BuzzCutNorman** [comment]
There is the sql target name conforming that was brought out in [SDK 0.13.0](https://github.com/meltano/sdk/discussions/1104).  If you override it by adding the `conform_name` function from SQLSink into your target's Sink and have it no nothing it might resolve the issues you are seeing currently.
```
    def conform_name(self, name: str, object_type: Optional[str] = None) -> str:
        """Conform a stream property name to one suitable for the target system.

        Transforms names to snake case by default, applicable to most common DBMSs'.
        Developers may override this method to apply custom transformations
        to database/schema/table/column names.

        Args:
            name: Property name.
            object_type: One of ``database``, ``schema``, ``table`` or ``column``.


        Returns:
            The name transformed to snake case.
        """
        # # strip non-alphanumeric characters, keeping - . _ and spaces
        # name = re.sub(r"[^a-zA-Z0-9_\-\.\s]", "", name)
        # # convert to snakecase
        # name = snakecase(name)
        # # replace leading digit
        # return replace_leading_digit(name)
        return(name)
```
