### ISSUE TITLE
[Bug]: Setting `add_record_metadata` should be surfaced as builtin target configuration

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1199]
### Singer SDK Version

0.14.0

### Python Version

NA

### Bug scope

Targets (data type handling, batching, SQL object generation, etc.)

### Operating System

NA

### Description

The flag is retrieved from config in https://github.com/meltano/sdk/blob/253851e005a92549684959f4f6150abc0617264b/singer_sdk/sinks/core.py#L187-L194

and it's documented in https://github.com/meltano/sdk/blob/1576b5c290396e8875c1daca8e8d920497467486/docs/implementation/record_metadata.md?plain=1#L1-L15

but the target's config schema is not aware of the setting.

This can be fixed by implementing `append_builtin_config` in the `Target` class to include that setting.

**Comment by BuzzCutNorman** [comment]
@edgarrmondragon I ran into [my mssql SDK target](https://github.com/BuzzCutNorman/target-mssql) asking for the `_sdc_table_version` to be added to tables in version 0.13.1 and 0.14.0 when I send full extracts from piplinewise `tap-postgres`.  

`2022-11-17 12:41:38,703 ALTER TABLE stuff.badges ADD _sdc_table_version INTEGER`

I haven't set anything for record metadata in my target to my knowledge.  I do know I set the following for `tap-postgres`
```
    metadata:
      '*':
        replication-method: FULL_TABLE
```

**Comment by edgarrmondragon** [comment]
@BuzzCutNorman yeah there's some overloading of _metadata_ here. In this case it refers to special columns added to tables by the target.

In particular `_sdc_table_version` is relevant for truncation in full-table replication, as you note.

The `metadata` you set in `meltano.yml` is the [Singer catalog metadata](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md#metadata) **for the tap**.

**Comment by pnadolny13** [comment]
@edgarrmondragon can you explain the `_sdc_table_version` attribute more? I've seen multiple users, most recently https://meltano.slack.com/archives/C01UTUSP34M/p1679672516968389?thread_ts=1679475632.154379&cid=C01UTUSP34M, ask for a timestamp or ID that allows them to differentiate records between different syncs. Usually batched_at/received_at/extracted_at are record level timestamps so they arent shared across all records in the sync i.e. you cant use a "group by".

Would `_sdc_table_version` do what we're looking for in this case? Is this related to activate version? If so, does this only get populated when a tap sends an activate version records?

**Comment by aaronsteers** [comment]
This is indeed the vehicle that is used for activate version. The spec is flexible on the contents, but generally it's only used in full table sync operations, and all records would have the epoch integer corresponding the sync star time.

**Comment by edgarrmondragon** [comment]
> Usually batched_at/received_at/extracted_at are record level timestamps so they arent shared across all records in the sync i.e. you cant use a "group by".

@pnadolny13 I think we could at least be more precise with `extracted_at` to make it more useful, and link it to the actual extraction time of a record.

In the generic case that could be when `get_records` is called. For REST streams, that could be when each page request is made, so all records in the same page would share a `extracted_at` value.

---

> ask for a timestamp or ID that allows them to differentiate records between different syncs

For this user request, we could also add another `_sdc_synced_at` (happy to hear better naming ideas! 😅) metadata column that would be set to the start time of the target process. That'd mean all records that were loaded in the same run would share this value, across tables. Do you think that would that work?

**Comment by pnadolny13** [comment]
> @pnadolny13 I think we could at least be more precise with extracted_at to make it more useful, and link it to the actual extraction time of a record.

@edgarrmondragon good point, I hadn't looked into it enough but I would expect it to act the way you described i.e. each record in a page request has the same timestamp.

> For this user request, we could also add another _sdc_synced_at (happy to hear better naming ideas! 😅) metadata column that would be set to the start time of the target process.

Yep thats exactly what I was looking for. Naming is tough, maybe `_sdc_sync_started_at`?
