### ISSUE TITLE
docs: sort and subdivide top-level docs pages

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1212]
The good news: The SDK has added **tons** of great features and we've been doing a good job documenting them.

The bad news: Our left-nav has gotten a bit out of control. 👀 

## Where we are now

As of now, we have 18 top-level docs entries in the left-nav.

<details>
<summary>Screenshot</summary>

<img width="332" alt="image" src="https://user-images.githubusercontent.com/18150651/203231443-98a715c8-8f35-4bdc-80eb-937cb26bc2b9.png">

</details>

## A possible path forward

Following the guidance for good docs, it would be great to take our existing headers and group them under the 4 type: guides, tutorials, discussions, and reference. Possibly:

- Dev Guide
	- [SDK Dev Guide](https://sdk.meltano.com/en/latest/dev_guide.html)
	- [Singer Tap Porting Guide](https://sdk.meltano.com/en/latest/porting.html)
	- [How to design a Sink](https://sdk.meltano.com/en/latest/sinks.html)
- How-to:
	- [SDK Code Samples](https://sdk.meltano.com/en/latest/code_samples.html)
	- [Frequently Asked Questions](https://sdk.meltano.com/en/latest/faq.html)
- Concepts
	- [Python Tips for SDK Developers](https://sdk.meltano.com/en/latest/python_tips.html)
	- [The Context Object](https://sdk.meltano.com/en/latest/context_object.html)
	- [Plugin Capabilities](https://sdk.meltano.com/en/latest/capabilities.html)
- Reference (Features)
	- [Inline Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html#)
	- [Batch Messages](https://sdk.meltano.com/en/latest/batch.html)
	- [Parent-Child Streams](https://sdk.meltano.com/en/latest/parent_streams.html)
	- [Stream Partitioning](https://sdk.meltano.com/en/latest/partitioning.html)
	- [Command Line Samples](https://sdk.meltano.com/en/latest/cli_commands.html)
- Reference (General)
	- [SDK Reference](https://sdk.meltano.com/en/latest/reference.html)
	- [SDK Implementation Details](https://sdk.meltano.com/en/latest/implementation/index.html)
	- [JSON Schema builder](https://sdk.meltano.com/en/latest/typing.html)
- Contribution Guide
	- [Contributing to the SDK](https://sdk.meltano.com/en/latest/CONTRIBUTING.html)

@sbalnojan, @tayloramurphy - What are your thoughts on this?

@edgarrmondragon - I have never tried to add additional layers of the docs in ReadTheDocs, and I'm aware this could be a heavy lift. Might not be able to prioritize immediately for that reason, but let me know what you think and if you happen to know of any path forward here.

Thanks, all!

**Comment by sbalnojan** [comment]
@aaronsteers I like it! I would move the "how-to design a sink" to the how-to section. This reorg would also open up the possibility of adding a nice tutorial on top.

**Comment by edgarrmondragon** [comment]
> I have never tried to add additional layers of the docs in ReadTheDocs, and I'm aware this could be a heavy lift.

@aaronsteers It's not, really. It's index.md + ToC + `:maxdepth:` all the way down 🙂. Also the `Reference (Features)` section feels more like guides than actual reference but it's a nit.

**Comment by tayloramurphy** [comment]
Yes - any love we can put into the SDK docs the better. Lots of folks use it and we want more!

**Comment by sbalnojan** [comment]
@aaronsteers I just looked at the pages again,

-I think your section "reference(features)" should go into "concepts" it is not a strict reference but rather explains and adds context. And these all seems like core concepts of the SDK.
- The page "Command Line Samples" I would move to Guides.

**Comment by edgarrmondragon** [comment]
@aaronsteers I think we can close this now?

**Comment by aaronsteers** [comment]
Indeed! Thanks, @edgarrmondragon 👍
