### ISSUE TITLE
[Bug]: Cookiecutter doesn't pass mypy for post_process method signature

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1224]
### Singer SDK Version

0.14.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Ubuntu

### Description

```
lint run-test: commands[5] | poetry run mypy tap_messagebird --exclude=tap_messagebird/tests        
tap_messagebird/client.py:77: error: Signature of "post_process" incompatible with supertype "Stream"    
```

This is generated from https://github.com/meltano/sdk/blob/main/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/%7B%7Bcookiecutter.library_name%7D%7D/%7B%25if%20'REST'%20%3D%3D%20cookiecutter.stream_type%20%25%7Dclient.py%7B%25endif%25%7D#L141

To fix change the signature to 

```
def post_process(self, row: dict, context: dict | None = None) -> dict | None:
```
And import annotations from future (if using a python version without those types)
```
from __future__ import annotations
```

Bump to https://github.com/meltano/sdk/issues/993

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/1648
