### ISSUE TITLE
[Bug]: Cookiecutter github action doesn't install dependencies with poetry for linting

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1225]
### Singer SDK Version

0.14.0

### Python Version

3.9

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Ubuntu

### Description

https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720 is an example of the failure

```
Run poetry run tox -e lint
  poetry run tox -e lint
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720#step:5:3).9.15/x6[4](https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.1[5](https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720#step:5:5)/x[6](https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720#step:5:6)4/lib
Creating virtualenv tap-messagebird-D0gzCIy0-py3.[9](https://github.com/MeltanoLabs/tap-messagebird/actions/runs/3566538853/jobs/5993107720#step:5:10) in /home/runner/.cache/pypoetry/virtualenvs
Command not found: tox
Error: Process completed with exit code 1.
```

Cookiecutter code that has this issue : https://github.com/meltano/sdk/blob/main/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/.github/workflows/%7B%25%20if%20cookiecutter.include_cicd_sample_template%20%3D%3D%20'GitHub'%20%25%7Dci_workflow.yml%7B%25endif%25%7D#L23-L29 

Doesn't have poetry install dependencies in order to run tox for linting

Bump to https://github.com/meltano/sdk/issues/993

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/1305
