### ISSUE TITLE
[Bug]: Cookiecutter github pytest --capture=no prints record objects to Action

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1226]
### Singer SDK Version

0.14.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Ubuntu

### Description

In the github action, the cookie cutter the pytest run has

```
poetry run pytest --capture=no
```
https://github.com/meltano/sdk/blob/main/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/.github/workflows/%7B%25%20if%20cookiecutter.include_cicd_sample_template%20%3D%3D%20'GitHub'%20%25%7Dci_workflow.yml%7B%25endif%25%7D#L55

At first glance that sounds good we don't want to capture the record output, but after testing the opposite is true. When `poetry run pytest --capture=no` is set pytest actually sends all stdout data to the terminal (as pytest isn't capturing the output anymore) thus printing RECORD objects which could be sensitive data. Not sure if this is a bug or not but for my case I really didn't want to see RECORDs in the output.

**Comment by aaronsteers** [comment]
@visch - Makes sense! I think originally the idea was to print detailed logs for debugging, but that only works for non-sensitive sources. 

Better to bias towards safe execution and disable that printed output.

**Comment by edgarrmondragon** [comment]
The new testing framework addressed this 🙂
