### ISSUE TITLE
Feature: Accept `ignore` glob patterns as standard tap config

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1240]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

This proposal would introduce a standard tap config option lik `ignored_patterns` or `ignored_streams`, or just `ignore`, which would accept glob-like input similar to `.gitignore`. This would operate similar to [`--exclude` in Meltano](https://docs.meltano.com/concepts/plugins#how-to-use-5) as the first-order, highest priority (de)selection logic. 

While this technically affects "selection" and "deselection", it actually would operate differently from both, and so we should avoid conflating them in discussion.

Like (de)selection logic:

- **Ignored streams and properties would not be replicated downstream.**
  - E.g., whether I "ignore" the `user` table or deselect it, either way it will not by synced to the target.
- **Ignore rules can also be inverted.**
  - E.g. If I set `"ignore": [ "*", "!users", "!customers" ]`, that is logically equivalent to deselecting all tables except 'users' and 'customers'. (Same as `.gitignore` convention.)

Unlike (de)selection logic:

- **Ignore rules always have higher precedence over selection.**
  - E.g. If I set `"ignore": [ "addresses.*", "*.*email*" ]`, then I can be 100% sure that no selection logic will later be introduced that pulls in any tables starting with "addresses*" or any columns containing the text "email". (Those physically would not be in the catalog to be selected.)
- **Ignore rules apply during discovery.**
   - E.g. If I set `"ignore": [ "information_schema-*" ]`, then my tap doesn't need to waste time analyzing any tables within `information_schema`.
 
A few nice things about accepting patterns and phrasing in the negative:

1. We're not overriding or changing `selection`/`deselection` logic. That logic still functions exactly according to Singer Spec.
2. Catalog output could take into account the `ignore` logic and save time during discovery - while also reducing the size of the generated catalog artifact.

When to use `ignore` instead of `selection`.

<table>
<tr>
	<td>Use Selection
	<td>Use Ignore
<tr>
	<td>When you want to select or deselect specific streams or properties.
	<td>When you want to exclude large group of streams or properties from being eligible for selection. (`information_schema-*,`*.email_address`, `broken_table.*`)
<tr>
	<td>To deselect streams and large data sources you don't need - with the understanding you can add them back easily in the future.
	<td>To systematically exclude streams you would never need or want included.
<tr>
	<td>To leave record of what is deselected in the catalog.
	<td>To suppress the streams or fields from the catalog entirely.
<tr>
	<td>To tell the tap to include fields that may not be included by default for that tap.
	<td>To tell the tap to ignore fields and tables it otherwise would try to scan.
</table>

### Challenges or reasons not to build

The biggest challenge is that there is not an obvious parser or glob pattern for stream and property ignore rules to follow. The easiest path would be to mimic the glob expressions that Meltano uses today for `--select` and `--exclude`. But escaping is always something to consider, and there may be other alternatives out there based on jsonpath or similar, which are more standards-based, even if less inherintly readable.

Another challenge is that by removing streams and properties from the catalog entirely, we miss an opportunity to document what exclusions have taken place. We could mitigate this by adding some annotations within to the catalog, such as a top-level `"ignored_streams": ["stream-a", "stream-b"]` and a stream-level `"ignored_properties": ["property-a", "property-b"]`.

Related to:

- #1234

**Comment by aaronsteers** [comment]
@kgpayne - Agreed: if we can use the same syntax as `--exclude` uses in Meltano today, then it could be a passthrough to the SDK if the tap has `ignore-patterns` (or similar) as a capability.

**Comment by kgpayne** [comment]
@aaronsteers great 👏 If we follow the Meltano select convention, I think your examples in the issue description reverse 🤔 I.e. "*" would become "select all" and `!users` and `!customers` would mean "exclude users and customers", as they are in Meltano? Just checking I am still following.

On naming, would it make sense to call these more generically `filter-patterns` or similar in the SDK config, as they support both include and exclude (via negation)?

**Comment by aaronsteers** [comment]
> @aaronsteers great 👏 If we follow the Meltano select convention, I think your examples in the issue description reverse 🤔 I.e. "*" would become "select all" and `!users` and `!customers` would mean "exclude users and customers", as they are in Meltano? Just checking I am still following.

Sorry. I did not mean to suggest to use `--select` and `--exclude`, and I still believe as I mentioned in my writeup that we should make this a new `ignore` feature and _not_ conflated with select/deselect.

My point was just that we can use the syntax of the rules, but applied to `ignore`.

**Comment by kgpayne** [comment]
@aaronsteers ah, ok. Thanks for clarifying.

How do you see the common ask of "limit discovery to selected streams" working with `ignore`? With full separation between selection and ignore pattern syntaxes (with ignore being the opposite of select), would it not be the case that a user would first have to use `meltano select tap-example users "*"` to select a stream and then additionally `meltano config tap-example ignore "!users.*"` then `meltano config tap-example ignore "*"` to ensure only the `users` stream is discovered? Repeated for each selection and remembering to negate their selection for `ignore`?

I agree that `ignore` patterns as described are different in _when_ they apply (`ignore` is applied pre-discovery in the SDK, and `select` applies post-discovery in Meltano on `catalog.json`) but _what_ the patterns refer to is the same - included or excluded streams and stream properties.

So by 'push down' I imagined that the select patterns, supported in the same format by both Meltano and the SDK, could be injected verbatim from `meltano.yml` `select` extra into the new setting in `config.json` to achieve the "limit discovery to selected streams" use case. This behaviour would be a feature of Meltano (behind a config extra flag in meltano (e.g. `limit_discovery_to_selection`) and would be a merge with any other patterns already defined in config directly, to allow users to leverage the other capabilities you mentioned. This would mean, for the common case, selection defined once (one place and in one format) then applied twice - pre and post discovery - with the option of configuring additional pre-discovery rules (including broad ignores) as needed.

Does that make sense? Maybe "limit discovery to selected streams" isn't a perfect fit for `ignore`?

**Comment by aaronsteers** [comment]
> With full separation between selection and ignore pattern syntaxes (with ignore being the opposite of select), would it not be the case that a user would first have to use `meltano select tap-example users "*"` to select a stream and then additionally `meltano config tap-example ignore "!users.*"` then `meltano config tap-example ignore "*"` to ensure only the `users` stream is discovered? Repeated for each selection and remembering to negate their selection for `ignore`?

No, I don't think it's that duplicative. I think in your example with just `users` table, this probably isn't the right way to implement that in real life - because in general we don't want to omit all surrounding tables - we actually do want them to show those as deselected when we look at the catalog or print it using something like `meltano select tap-something --list --all`.

That said, if we really want to use ignore for this use case, I don't think you need anything in the select rules, except '*' if the tap does not select its streams by default. So, the ignore rule would just be `['*', '!users']` - and to add one more table you'd ignore `['*', '!users', '!customers']`. Again, this isn't really the main use case for ignore, since `select` is a better match for this use case.

A better-matched use case would be if we have a tap with a three-part stream name containing '<db>-<schema>-<table>', and the source has three databases: 'prod', 'test', and 'cicd'. We want to make sure when we select the 'users' table, we're _only_ getting the version from prod. Essentially we want to treat the tap as if it did not contain the `test` or `cicd` databases at all. It is not that we want to _select_ or _deselect_ those other databases, but we want to basically insulate ourselves from them and pretend they don't exist. So an ignore rule of either `['test-*', 'cicd-*']` or inversely `['*', '!prod']` will have the effect of making it look like it is only returning results from 'prod', even if the tap itself is able to view and extract from all three databases.

That's very similar to the default behavior for excluding `information_schema` - not only do we want to save time from having to scan it, but we want to pretend like those tables just don't exist at all for the purposes of our catalog construction.

**Comment by kgpayne** [comment]
Still relevant, in so far as it relates to per-stream config (#1350).
