### ISSUE TITLE
[Bug]: Cookiecutter for SQL taps doesn't import proper modules in client.py

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1250]
### Singer SDK Version

0.14.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Ubuntu

### Description

1. Cookiecutter as a SQL type tap
2. https://github.com/meltano/sdk/blob/main/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/%7B%7Bcookiecutter.library_name%7D%7D/%7B%25if%20'SQL'%20%3D%3D%20cookiecutter.stream_type%20%25%7Dclient.py%7B%25endif%25%7D#L53 Iterable, Optional, Dict, and Any are not defined 

Bump to https://github.com/meltano/sdk/issues/993

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/1648
