### ISSUE TITLE
[Bug]: Cookiecutter SQL Tap doesn't list a default_stream_class any longer

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1251]
### Singer SDK Version

0.14.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Linux

### Description

1. Create a new cookiecutter tap as a SQL Type
2. In tap.py you will not see a default_stream_class listed

Run the tap and you'll get something like
`AttributeError: 'TapDuckDB' object has no attribute 'default_stream_class'`

Bump to https://github.com/meltano/sdk/issues/993

**Comment by edgarrmondragon** [comment]
Addressed by https://github.com/meltano/sdk/pull/1648
