### ISSUE TITLE
Bug: for SQL taps, type failsafe to string should also cast the value

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1255]

**Comment by visch** [comment]
https://github.com/MeltanoLabs/tap-postgres/pull/7/files 

I know mssql had a PR and I think oracle had it as well

**Comment by BuzzCutNorman** [comment]
I was alerted yesterday of the failsafe data type string causing a target error.  Here are the links for the issue and slack discussion.

https://github.com/BuzzCutNorman/tap-mssql/issues/8
https://meltano.slack.com/archives/C01TCRBBJD7/p1670312879839659
