### ISSUE TITLE
[Bug]: SQL Stream can’t adapt type ‘Column’

### ISSUE THREAD

**Issue by crowemi** [meltano/sdk#1268]
### Singer SDK Version

0.15.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Mac OS

### Description

I'm trying to use the SDK to incrementally query a tap (tap-postgres) on a date replication column, and the result is generating this error in the `SQLStream.get_records` method:  

`(psycopg2.ProgrammingError) can't adapt type 'Column'`

It appears that we're trying to pass the Column object as a bindparam and sqlalchemy isn't converting the object properly in the generated SQL statement.

---

In addition, when changing the input of the replication key bindparam from `Column` object to `Column.name`, the SQL statement generates the column name quoted, which doesn't return the expected incremental record count. e.g.

`where 'replication_column' = value`

---

I've tested locally removing the column name as a bindparam and instead using string interpolation to add Column.name to the text statement. This seems to work as expected. e.g.

`where replication_column = value`

### Code

https://github.com/meltano/sdk/blob/main/singer_sdk/streams/sql.py#L190-L195

```python
query = query.where(
   sqlalchemy.text(":replication_key >= :start_val").bindparams(
      replication_key=replication_key_col, start_val=start_val
   )
)
```

**Comment by crowemi** [comment]
Proposed solution:

```
                query = query.where(
                    sqlalchemy.text(f"{replication_key_col.name} >= :start_val").bindparams(
                        start_val=start_val
                    )
                )
```

**Comment by visch** [comment]
Here's a fix implemented. @crowemi  merging this for `tap-postgres` now you should be good to go on that side
