### ISSUE TITLE
[Feature]: Target json schema validation should include stream name

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1272]
### Feature scope

Targets (data type handling, batching, SQL object generation, etc.)

### Description

When you get an exception like ` jsonschema.exceptions.ValidationError` the exception is really good about listing out which json key the offending value is at ie ` Failed validating 'type' in schema['properties']['powerUps']['items']: {'properties': {}, 'type': 'object'}   On instance['powerUps'][0]:   'cardAging'` , but it doesn't have the stream name which makes it harder to fix than this needs to be. 

I did something similar in target-jsonl.  https://github.com/andyhuynh3/target-jsonl/commit/681242f73897c2b08d1e9432578c15e37520f6ff 

Probably not too hard :D

**Comment by edgarrmondragon** [comment]
Thanks for creating this @visch!

**Comment by edgarrmondragon** [comment]
Still relevant and still open to contributions

**Comment by edgarrmondragon** [comment]
The log message in https://github.com/meltano/sdk/pull/2421 is emitted by the `<tap name>.<stream name>` logger.
