### ISSUE TITLE
[Feature]: add_record_metadata should be in the generated Readme

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1285]
### Feature scope

Targets (data type handling, batching, SQL object generation, etc.)

### Description

https://github.com/meltano/sdk/blob/main/singer_sdk/sinks/core.py#L194 
defaults to false, this should automatically be put into the readme generation just like stream_maps are! :D

**Comment by edgarrmondragon** [comment]
This is good first issue for anyone looking to contribute.

- Add the config schema, similar to https://github.com/meltano/sdk/blob/90dcd39858fa5f1238995323b86349ed306f1e66/singer_sdk/helpers/capabilities.py#L51-L57

- Append to the builtin config, similar to https://github.com/meltano/sdk/blob/90dcd39858fa5f1238995323b86349ed306f1e66/singer_sdk/target_base.py#L591-L619

**Comment by edgarrmondragon** [comment]
Still relevant

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/1881
