### ISSUE TITLE
change: Exception raised when input line is not a valid singer message should be more specific

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1288]
The exception raised here (`Exception`) is too generic. A more concrete exception class would be nice

_Originally posted by @edgarrmondragon in https://github.com/meltano/sdk/pull/1287#discussion_r1053833567_

**Comment by visch** [comment]
Yes 💯, a good place to start for these if you want a list of them is in the target tests for postgres

**Comment by edgarrmondragon** [comment]
This was done in https://github.com/meltano/sdk/commit/adcd9175d0d59d5b7a273985afd3b1216aac03ee
