### ISSUE TITLE
[Bug]: --config ENV does not work for non-string config properties

### ISSUE THREAD

**Issue by Jack-Burnett** [meltano/sdk#1310]
### Singer SDK Version

0.13.1

### Python Version

3.10

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

MacOS

### Description

--config ENV lets us pass in values via environment variables in addition to in config files.
However, if the property being passed in is not a string then it will fail to validate against the schema.

The method which could address this can be found here;
https://github.com/meltano/sdk/blob/48dc863e2257ab308413ae74dd10e6575c239ae8/singer_sdk/configuration/_dict_config.py#L19

Since it has access to the schema, we could modify it so it attempts to parse the value based on the schema. I think integer/float/boolean would all be useful to support.

**Comment by edgarrmondragon** [comment]
@Jack-Burnett I think this would be valuable, but may not be something we can prioritize internally. PRs are welcome, though 😄.
