### ISSUE TITLE
Feature: stream_name_splits toggle in targets

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1319]
### Feature scope

Targets (data type handling, batching, SQL object generation, etc.)

### Description

For SQL Targets we splits streams based on dash's see https://github.com/meltano/sdk/blob/main/singer_sdk/sinks/sql.py#L67-L103 , this can be confusing for folks we aren't expecting this or who have a source like `tap-dynamodb` that have streams with dash's in the name by design, but the dash's do not represent `<schema>-<table>` . So I think we should add a flag for `stream_name_splits` 

Example implementation here  https://github.com/MeltanoLabs/target-postgres/pull/59

Slack thread: https://meltano.slack.com/archives/C01TCRBBJD7/p1671688563297449

**Comment by edgarrmondragon** [comment]
Still relevant
