### ISSUE TITLE
[Feature]: Remove type-requests for targets not using rest

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1340]
### Feature scope

Targets (data type handling, batching, SQL object generation, etc.)

### Description

From this PR https://github.com/MeltanoLabs/target-postgres/pull/85 we found that type-requests isn't needed for `target-postgres` 

              > Nice.
> 
> We should probably also consider making this library conditional in the cookie cutter.
> 
> (Not to self: @aaronsteers)
> 
> Cc @kgpayne, @edgarrmondragon 

@aaronsteers yeah, that makes sense. We can exclude it if the user selects SQL in the cookiecutter prompt.

_Originally posted by @edgarrmondragon in https://github.com/MeltanoLabs/target-postgres/issues/85#issuecomment-1399098456_

**Comment by edgarrmondragon** [comment]
This is a quick win. I'll start a PR.
