### ISSUE TITLE
refactor: collect connection methods onto a `Connector` class for use by Tap/Target and Streams/Sinks

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1355]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Currently the helper methods for auth, constructing requests and parsing responses (including pagination etc.) are implemented as methods on the various `Stream` child classes (e.g. `RESTStream`). This has been convenient so far, but has several drawbacks (enumerated in #317 for the REST case).

In implementing SQL Taps/Targets, we introduced the concept of a `SQLConnector` to handle some (but not all) interactions with remote systems. Notably [connection handling](https://github.com/meltano/sdk/issues/1352) is not yet centralised, but the `SQLConnector` architecture does at least allow the Tap access to the connector to make requests (e.g. for discovery).

## Proposal

- We create a set of `Connector` classes responsible for _all_ interactions with remote systems, consolidating methods for auth, request/response, throttling/backoff, request quota/limit management, connection pooling etc.
- Instances of the connector are accessible to both Tap/Target and Stream/Sink classes.
- The developer of an individual Tap/Target can decide if a singleton connector is appropriate (e.g. for SQL connection pooling) or if each Stream/Sink can instantiate its own connector (e.g. for some APIs).

This might look something like:

```python
from singer_sdk import Tap
from singer_sdk.connector import Connector, RESTConnector

from .streams import UsersStream, GroupsStream

STREAM_TYPES = [
    UsersStream,
    GroupsStream,
]

class ExampleTap(Tap):
        _connector = None

    def get_connector(self) -> Connector:
        """Get a configured connector for this Tap.
        
        Connector returned can either be a singleton (one instance used by the Tap and Streams)
        or a new instance on every call, according to the particular use case and remote system.
        """
        # create a singleton connector on first access
        if not self._connector:
            self._connector = RESTConnector(
                **self.config
            )
        return self._connector

    def discover_streams(self) -> List[Stream]:
        """Return a list of discovered streams.

        This method could optionally make use of `self.get_connector()` to make requests to
        the remote system to discover streams.
        """
        return [stream_class(tap=self, connector=self.get_connector()) for stream_class in STREAM_TYPES]
```

cc @edgarrmondragon @aaronsteers

**Comment by qbatten** [comment]
I think it'd make sense to have SQLTap do this by default. Does that sound right to you, @kgpayne? If so, I can make a PR for it. 

We're doing this in tap-postgres already in this PR](https://github.com/MeltanoLabs/tap-postgres/pull/22). (I just added a comment to my PR there that explicitly links to this issue bc I realized that that Github-metedata-breadcrumb was missing and it seems useful!)
