### ISSUE TITLE
[Docs]: Add usage example of `Stream.get_starting_timesamp()`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1372]
### Documentation type

How-to guides

### Description

https://meltano.slack.com/archives/C01PKLU5D1R/p1675116342431159?thread_ts=1674850558.848759&cid=C01PKLU5D1R

> I think a bit more documentation in the [Meltano Singer SDK](https://sdk.meltano.com/en/main/index.html) would be a great improvement to the user experience. I think either sometime in the [SDK Code Samples](https://sdk.meltano.com/en/main/code_samples.html#sdk-code-samples) with example of an implementation of [get_starting_timesamp()](https://sdk.meltano.com/en/latest/classes/singer_sdk.Stream.html#singer_sdk.Stream.get_starting_timestamp) or a dedicated section similar to [Parent-Child Streams](https://sdk.meltano.com/en/main/parent_streams.html#parent-child-streams) would be awesome.

**Comment by flexponsive** [comment]
I just worked with [get_starting_replication_key_value()](https://sdk.meltano.com/en/latest/classes/singer_sdk.Stream.html#singer_sdk.Stream.get_starting_replication_key_value) and would be happy to contribute a section to the docs like the parent-child streams example.

Topics I would include based on my experience:
- how to register the replication method and key in the stream
- using starting key/timestamp to adapt the query in a REST tap
- how create a state.json file for testing the tap and manually run an incremental replication

(From my project, here is an [example of get_starting_replication_key_value() in action](https://github.com/flexponsive/tap-eu-ted/blob/d606d75d78c9965ea25d9e83f05ae7479172b0b8/tap_eu_ted/client.py#L51))

**Comment by edgarrmondragon** [comment]
Hey @flexponsive! We'd welcome your contribution, let me know if you have any questions and https://sdk.meltano.com/en/latest/CONTRIBUTING.html should help you get started 😄
