### ISSUE TITLE
bug: Consider moving cookiecutter tests to root of generated project to facilitate test discovery

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1377]
### Singer SDK Version

0.19.0

### Python Version

NA

### Bug scope

Other

### Operating System

Any

### Description

See https://github.com/meltano/sdk/issues/1370#issuecomment-1412430065

> Aha! Yes, that solved this. I also had to update pytest and, along with that, move the tests folder out into the rootdir of the repo, from `tap-postgres/tap-postgres/tests/` -> `tap-postgres/tests/`. Thank you!!

**Comment by qbatten** [comment]
Specifically, pytest >=4.0 requires you to do this if you're defining pytest_plugins https://docs.pytest.org/en/7.1.x/deprecations.html#pytest-plugins-in-non-top-level-conftest-files. AIUI.

**Comment by edgarrmondragon** [comment]
Thanks for the additional context @qbatten!

**Comment by menzenski** [comment]
I am seeing this issue with SDK version 0.22.1 and `tests/` in the top level repository directory.

Tests directory: https://github.com/menzenski/tap-mongodb/blob/main/tests/core_test.py
Failing tests: https://github.com/menzenski/tap-mongodb/actions/runs/4635115290/jobs/8201896087#step:7:24

**Comment by edgarrmondragon** [comment]
@menzenski were you able to fix this by adding a `tests/conftest.py`?
