### ISSUE TITLE
[Bug]: Tap not receiving state when run via Meltano

### ISSUE THREAD

**Issue by LukePammant** [meltano/sdk#1384]
### Singer SDK Version

0.19.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Windows & WSL2 (Ubuntu 20.2)

### Description

I'm running into the issue where the state passed into the tap/streams is empty when running via Meltano. My tap is based on this [Google Analytics tap](https://github.com/MeltanoLabs/tap-google-analytics/tree/dependabot/pip/singer-sdk-0.19.0) that was using "^0.4.2" of the singer-sdk. I made a new tap based on the latest template in v0.19.0 and copied over the dependencies from the pytporject.toml and ran `poetry install` to get everything up to date. 

I can see that the tap's capabilities include "state" if I log out the `self.capabilities` and can see that the stream/tap is _writing_ to the state table in Postgres so it appears to have the correct DB settings and is able to access the database. I can also see that the state is correct via: `meltano --environment prod state get daily-ga-lcp-load`

But when I run the import via `meltano elt ...` and log `self.state` from the tap or stream I get an empty object (`{}`). This is the command I'm running: `meltano --environment prod elt --state-id daily-ga-lcp-load tap-ga--report-lcp target-postgres --transform run`

When I run the tap directly via `tap-rb-google-anlytics --config config.json --state state.json --catalog catalog.json` as recommended by @visch on [this issue](https://github.com/meltano/meltano/issues/7191) I can see the state in my tap and the streams so I don't believe it is an issue with my tap/stream code.

It only appears to be when running via meltano with `meltano invoke my-tap --state-id my-id`, or `meltano elt my-tap --state-id my-id`, or even when running via airflow.

Thanks for any help!

**Comment by tayloramurphy** [comment]
@aaronsteers @seth-meltano if we could have an engineer look at this that'd be great. Note the linked Meltano issue as well.

**Comment by aaronsteers** [comment]
@LukePammant - it looks like you've done everything right on the tap side. In your meltano.yml file though, you'll need to also declare capabilities, including `state` to enable incremental sync and bookmarks.

**Comment by LukePammant** [comment]
@aaronsteers - ah I see now. @visch mentioned about the meltano.yml file but I thought talking about it in regards to the file in the custom tap folder (not in my meltano project folder). 

I've added the capabilities to the `extractor` definition in the `meltano.yaml` in my meltano project and it looks like its working now. Thank you!

**Comment by visch** [comment]
> ### Singer SDK Version
> 0.19.0
> 
> ### Python Version
> 3.8
> 
> ### Bug scope
> Taps (catalog, state, stream maps, etc.)
> 
> ### Operating System
> Windows & WSL2 (Ubuntu 20.2)
> 
> ### Description
> I'm running into the issue where the state passed into the tap/streams is empty when running via Meltano. My tap is based on this [Google Analytics tap](https://github.com/MeltanoLabs/tap-google-analytics/tree/dependabot/pip/singer-sdk-0.19.0) that was using "^0.4.2" of the singer-sdk. I made a new tap based on the latest template in v0.19.0 and copied over the dependencies from the pytporject.toml and ran `poetry install` to get everything up to date.
> 
> I can see that the tap's capabilities include "state" if I log out the `self.capabilities` and can see that the stream/tap is _writing_ to the state table in Postgres so it appears to have the correct DB settings and is able to access the database. I can also see that the state is correct via: `meltano --environment prod state get daily-ga-lcp-load`
> 
> But when I run the import via `meltano elt ...` and log `self.state` from the tap or stream I get an empty object (`{}`). This is the command I'm running: `meltano --environment prod elt --state-id daily-ga-lcp-load tap-ga--report-lcp target-postgres --transform run`
> 
> When I run the tap directly via `tap-rb-google-anlytics --config config.json --state state.json --catalog catalog.json` as recommended by @visch on [this issue](https://github.com/meltano/meltano/issues/7191) I can see the state in my tap and the streams so I don't believe it is an issue with my tap/stream code.
> 
> It only appears to be when running via meltano with `meltano invoke my-tap --state-id my-id`, or `meltano elt my-tap --state-id my-id`, or even when running via airflow.
> 
> Thanks for any help!
> 
> ### Code
> _No response_

This has caught me more than once and it is a big drain on time, you're not the only one! It's hard to tell this is happening

Glad you found it!!
