### ISSUE TITLE
feat: support reading standard `__version__` module attr when reporting `--about` version

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1403]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Python packaging is messy, and so our implementation of sourcing the plugin version (to report in `--about`) from package metadata does not work in several scenarios (discovered in this [PR](https://github.com/meltano/sdk/pull/1254)). It would help if our implementation would check the standard module `__version__` attribute before trying other means to infer a version.

`poetry-dynamic-versioning` supports substituting the value of `__version__` by default, so this would be the primary mechanism used in MeltanoLabs variants for reporting the plugins version.

e.g.

```python
# tap-snowflake/__init__.py
__version__ = "0.0.0"  # poetry-dynamic-versioning will replace this value on release

**Comment by rafalkrupinski** [comment]
__version__ is deprecated in favour of `importlib.metadata.version`

**Comment by WillDaSilva** [comment]
@rafalkrupinski This issue is not proposing that we don't use `importlib.metadata`. Rather it suggests an alternative based on common convention that we could check because we are not always able to obtain the package version using `importlib.metadata`.
