### ISSUE TITLE
feature: Use `pre-commit` in cookiecutters instead of direct dependencies on `black`, `isort`, etc.

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1405]
### Feature scope

Other

## Advantages

- Fewer headaches around incompatible dependencies by having `pre-commit` manage a virtualenv for each tool (see #1402)
- Can integrate with pre-commit.ci for autofixes and autoupdates

## Disadvantages

- One more tool to manage for developers (e.g. `poetry run isort` vs `pre-commit run isort --all-files`

**Comment by rafalkrupinski** [comment]
Using pre-commit to manage dependencies is a headache. There's no lock file, and since some package use others' internal names, pre-commit often unexpectedly fails when a new patch version changes something.

https://github.com/OCA/oca-addons-repo-template/issues/175#issue-1466067857

**Comment by rafalkrupinski** [comment]
Ah, sorry, I didn't mean to promote nix, I find it to heavy too. I only meant to point out problems that pop-out unexpectedly with pre-commit, and I just happen to know that link :)
Glad you have it worked out

**Comment by rafalkrupinski** [comment]
How about [nox](https://nox.thea.codes/en/stable/)?

**Comment by WillDaSilva** [comment]
@rafalkrupinski `nox` is more of a replacement for `tox` than `pre-commit`. Additionally, it doesn't have/use a lockfile, which was your original issue with this suggestion to use `pre-commit` as the source of truth for linting dependencies.

**Comment by edgarrmondragon** [comment]
I agree with @WillDaSilva. Reproducibility and stability are desired properties for any workload, but I think we can tolerate a slight lack of both for linters in favor of avoiding dependency conflicts with actual package dependencies.

Closed by https://github.com/meltano/sdk/pull/1648
