### ISSUE TITLE
[Bug]: SQL DATE columns causing jsonschema ValidationError Failed validating 'format': 'date'

### ISSUE THREAD

**Issue by BuzzCutNorman** [meltano/sdk#1414]
### Singer SDK Version

0.19.0

### Python Version

3.9

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Windows

### Error Info
Issue with `DATE` columns returning time info and not passing JSON schema validation when sent to a target.  This error was found running `meltano run tap-mssql target-mssql` when the tap is reading from the `AdventureWorks2019` database table `HumanResources-EmployeeDepartmentHistory`.  The column `StartDate` which is a MS SQL data type of `DATE` is the offending column.
```
023-02-08T20:07:25.814139Z [info     ]     raise error                cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.829802Z [info     ] jsonschema.exceptions.ValidationError: '2009-01-14T00:00:00+00:00' is not a 'date' cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.829802Z [info     ]                                cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.829802Z [info     ] Failed validating 'format' in schema['properties']['StartDate']: cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.829802Z [info     ]     {'format': 'date', 'type': ['string']} cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.829802Z [info     ]                                cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.845392Z [info     ] On instance['StartDate']:      cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.845392Z [info     ]     '2009-01-14T00:00:00+00:00' cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-08T20:07:25.861020Z [error    ] Loader failed
```

When the table is queried in SSMS you do not see a time stamp after the date.  If you run `meltano invoke tap-mssql` you can see the time stamp of `T00:00:00+00:00` is present after each date.
|BusinessEntityID|	DepartmentID|	ShiftID|	StartDate|	EndDate|	ModifiedDate|
|------------------|-------------------|-------------|-------------|---------------|----------------|
|1	                   |16	                |1	            |2009-01-14|NULL 	      |2009-01-13 00:00:00.000|
```
2023-02-08 12:04:03,402 | INFO     | tap-mssql            | Beginning full_table sync of 'HumanResources-EmployeeDepartmentHistory'...
2023-02-08 12:04:03,402 | INFO     | tap-mssql            | Tap has custom mapper. Using 1 provided map(s).
{"type": "SCHEMA", "stream": "HumanResources-EmployeeDepartmentHistory", "schema": {"properties": {"BusinessEntityID": {"minimum": -2147483648, "maximum": 2147483647, "type": ["integer"]}, "DepartmentID": {"minimum": -32768, "maximum": 32767, "type": ["integer"]}, "ShiftID": {"minimum": 0, "maximum": 255, "type": ["integer"]}, "StartDate": {"format": "date", "type": ["string"]}, "EndDate": {"format": "date", "type": ["string", "null"]}, "ModifiedDate": {"format": "date-time", "type": ["string"]}}, "type": "object", "required": ["BusinessEntityID", "DepartmentID", "ShiftID", "StartDate", "ModifiedDate"]}, "key_properties": ["BusinessEntityID", "StartDate", "DepartmentID", "ShiftID"]}
{"type": "RECORD", "stream": "HumanResources-EmployeeDepartmentHistory", "record": {"BusinessEntityID": 1, "DepartmentID": 16, "ShiftID": 1, "StartDate": "2009-01-14T00:00:00+00:00", "EndDate": null, "ModifiedDate": "2009-01-13T00:00:00+00:00"}, "time_extracted": "2023-02-08T20:04:03.464734+00:00"}
```

### findings
I found where the extra `T00:00:00+00:00` is being added.  In the `singer_sdk\helpers\_typing.py` file there is a function called `_conform_primitive_property`.  In that function it looks for `datetime.date` and appends `T00:00:00+00:00` to the ISO formatted string.  If I remove the append portion and the function returns just the ISO format date the data passes JSON validation.  The data looks correct when it is inserted into the target table.

There is a little more info in the issue I raised in the `buzzcutnorman--tap-mssql` repository.
https://github.com/BuzzCutNorman/tap-mssql/issues/21 

### Code

```python
def _conform_primitive_property(elem: Any, property_schema: dict) -> Any:
    """Converts a primitive (i.e. not object or array) to a json compatible type."""
    
    ...
    
    elif isinstance(elem, datetime.date):
        return elem.isoformat() + "T00:00:00+00:00"
    
    ...
```

**Comment by edgarrmondragon** [comment]
Hmm, yeah this feels like a bug but I'm a bit surprised that it hasn't come up before. Adding the extra `T00...` has been there from the first RC of the singer SDK: https://github.com/meltano/sdk/commit/e66de5d3b90f93288d1e84206eaf91a3116e2823 so maybe @aaronsteers has more context on why this was added back then.

**Comment by BuzzCutNorman** [comment]
@edgarrmondragon I wanted to check in to see if after reviewing context it was decided it best to leave this as is or if would be ok to submit a PR with a possible fix? Thanks 🙏

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I wanted to check in to see if after reviewing context it was decided best to leave this as is or if it would be ok to submit a PR with a possible fix? Thanks 🙏

@BuzzCutNorman A PR is welcome but I would like to consider if we can change this without breaking it for users who rely on this behavior. cc @kgpayne

**Comment by BuzzCutNorman** [comment]
> @BuzzCutNorman A PR is welcome but I would like to consider if we can change this without breaking it for users who rely on this behavior. cc @kgpayne

@edgarrmondragon I completely respect and agree with your concern.  I just was able to resolve this issue by placing a fix into the `post_process` method I recently added to `tap_mssql.mssqlStream` for encoding of `varbinary` columns. 🎉 I am sorry I didn't figure this out before.  Thank you for taking the time to look into this. 🙏

cc @kgpayne
