### ISSUE TITLE
[Docs]: feature/docs? - Best practice for Reports

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1427]
### Documentation type

How-to guides

### Description

This may also be a few features requests for the SDK. I've seen a number of questions hit Slack about the type of requests that need to go request a Report from an API. 

Here's an implementation I did. 
https://github.com/AutoIDM/tap-indeed/blob/main/tap_indeedsponsoredjobs/streams.py#L61-L213

Most generic things from this is probably [`_sdc_line_number`](https://github.com/AutoIDM/tap-indeed/blob/main/tap_indeedsponsoredjobs/streams.py#L210-L213 ) encourage keeping the line number from the dataset in the data.  

The [`EmployerStatsReport`](https://github.com/AutoIDM/tap-indeed/blob/main/tap_indeedsponsoredjobs/streams.py#L61) class is pretty hacky as it overrides a bunch of methods to prevent some of the standard `Stream` functionalities in order to use other standard `RestStream` functionalities  

Relevant slack threads I think:
* https://meltano.slack.com/archives/CMN8HELB0/p1676486225768239
* https://meltano.slack.com/archives/C01PKLU5D1R/p1675340377694479
* https://meltano.slack.com/archives/CMN8HELB0/p1676059253027029
* https://meltano.slack.com/archives/CMN8HELB0/p1675995006892769

**Comment by tayloramurphy** [comment]
@visch in this case a report is a CSV?

**Comment by visch** [comment]
> @visch in this case a report is a CSV?

Yes where you're calling endpoints to request report csvs. It seems like a semi-common pattern with a number of folks asking about it. Maybe not necessarily the CSV portion but I'm not sure.

**Comment by edgarrmondragon** [comment]
Still relevant
