### ISSUE TITLE
ci: E2E cookiecutter tests use a local reference of `singer-sdk` instead of a PyPI one

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1444]
### Singer SDK Version

0.20.0

### Python Version

3.6 (deprecated)

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

NA

### Description

This way we can test the templates with the latest state of the library and work correctly in version bump PRs: https://github.com/meltano/sdk/actions/runs/4235758709

**Comment by edgarrmondragon** [comment]
cc @flexponsive curious if you have any suggestions

**Comment by flexponsive** [comment]
You are right it makes sense to use a local reference in end-to-end tests always. Apparently poetry solves this problems with [editable mode](https://python-poetry.org/docs/cli#add):

```
[tool.poetry.dependencies]
my-package = {path = "../my/path", develop = true}
```

I submitted a PR replacing the singer-sdk dependency in place using sed

**Comment by edgarrmondragon** [comment]
Thanks @flexponsive!
