### ISSUE TITLE
[Bug]: Inconsistent config naming in cookiecutter

### ISSUE THREAD

**Issue by radbrt** [meltano/sdk#1452]
### Singer SDK Version

0.21.0

### Is this a regression?

- [ ] Yes

### Python Version

NA

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Mac

### Description

In the cookiecutter tap template, one of the configs in `tap.py` is `auth_token`: https://github.com/meltano/sdk/blob/774a17664a139b966de5c80ed69aab2c161e2752/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/%7B%7Bcookiecutter.library_name%7D%7D/tap.py#L26

In the `client.py` file for REST targets however, the code references a config named `api_key`: https://github.com/meltano/sdk/blob/774a17664a139b966de5c80ed69aab2c161e2752/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/%7B%7Bcookiecutter.library_name%7D%7D/%7B%25if%20'REST'%20%3D%3D%20cookiecutter.stream_type%20%25%7Dclient.py%7B%25endif%25%7D#L89

My hunch is that `client.py` for REST taps should reference `auth_token` as that is what the graphQL template does.

If anyone agrees, I'll make a PR. As it is today, this config name has to be changed for the tap to run.

**Comment by tayloramurphy** [comment]
@aaronsteers @edgarrmondragon can you add your thoughts on this?

**Comment by edgarrmondragon** [comment]
Yeah, we should change the `client.py` template to use `auth_token` instead, for consistency.

I'd say a PR is welcome @radbrt 🙂
