### ISSUE TITLE
docs: Reference state partitioning in stream partitioning page

### ISSUE THREAD

**Issue by josephlozano** [meltano/sdk#1474]
### Documentation type

Explanation

### Description

I was learning about [stream partitioning](https://sdk.meltano.com/en/latest/partitioning.html) and I thought it would be helpful to reference [state partitioning](https://github.com/meltano/sdk/blob/main/docs/implementation/state.md#partitioned-state) here as well. A partitioned stream must have a partitioned state so I think it would be useful to clarify that relationship for others viewing the page.

**Comment by edgarrmondragon** [comment]
Still open to contributions
