### ISSUE TITLE
chore: nox deprecation The `--dev` option is deprecated, use the `--with dev` notation instead.

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1479]
Should be a simple one! Just noticed it running test on the sdk for the first time locally

**Comment by WillDaSilva** [comment]
Closing because there is nothing we can do within the SDK to address this. This is an issue within `nox-poetry` that has yet to be resolved:
- https://github.com/cjolowicz/nox-poetry/issues/977

Thanks for reporting nonetheless. Hopefully they fix this before it becomes a problem.

**Comment by visch** [comment]
@WillDaSilva  you're fast :D Sorry about the needless issue :D
