### ISSUE TITLE
Migrate Docs Website Google Analytics to GA4

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#1489]
Related to https://github.com/meltano/internal-data/issues/89

We need to migrate to the new GA4 property. This is my understanding of what we need to do:

> It sounds like we click some buttons in the GA UI to create a new GA4 "property" (i.e. entity in GA, each one of our websites is currently its own property) for the thing we want to migrate, if we dont do this manually theyll soon do it for us automatically. Then to activate it and start sending our events to the new GA4 we need to update our javascript snippets that send the events and include a "tag" manually or use google tag manager (I'm not yet sure what that is). After that point we'll have events flowing to our new "property".

**Comment by edgarrmondragon** [comment]
I think we lost tracking when we moved to the `furo` theme, since [`sphinx_rtd_theme` supported it out-of-the-box](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html). The new theme makes adding this a bit harder, but not impossible:

- https://github.com/pradyunsg/furo/discussions/401
- https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

cc @kgpayne

**Comment by kgpayne** [comment]
@edgarrmondragon @pnadolny13 I did spot that `furo` doesn't support GA out-of-the-box when we migrated, and [added](https://github.com/meltano/sdk/blob/main/docs/_templates/base.html#L8) the GA script and config to our `base.html` at the time. Not sure if the script is doing its job though - @pnadolny13 are we still getting SDK Docs visit data in GA?

**Comment by pnadolny13** [comment]
@kgpayne I think it is doing its job! I can see traffic in the GA console. The interesting thing though is that I cant find that ID anywhere `GTM-WHJMBX2` 🤔 . I'm not super versed in GA but when I looked around for installation instructions it wants me to to use `G-84WQMSLGTE` to send data to GA for the SDK docs. Do you remember where that ID came from? I'm wondering if thats an older ID thats still linked for backwards compatibility on the GA side.

Other than the ID confusion it seems like this issue might already be complete though.

**Comment by edgarrmondragon** [comment]
@pnadolny13 The `GTM-WHJMBX2` id comes from https://github.com/meltano/sdk/pull/1218, when we changed to Tag Manager.
