### ISSUE TITLE
Feat: add the `json` module to stream maps context

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1502]
Per

- #1500 

Specifically, `json.loads()` and `json.dumps()` would be helpful.

**Comment by edgarrmondragon** [comment]
@aaronsteers Do we need all members of `json` or can we do with just `json.loads` and `json.dumps`?

**Comment by aaronsteers** [comment]
> @aaronsteers Do we need all members of `json` or can we do with just `json.loads` and `json.dumps`?

Good question. Want to add thoughts in the PR?

I like adding `json` because it's simplest and doesn't require retraining from what users would expect. But I don't mind if we want to implement in another way - especially if for security reasons we want to keep to "safe" implementations only.

**Comment by edgarrmondragon** [comment]
Still relevant

**Comment by edgarrmondragon** [comment]
Things to keep in mind for anyone that's interested in contributing this:

* How to communicate schema types? Perhaps aliases of `json.loads` should be used, which the SDK can identify as specific types, e.g. `parse_json_object`, `parse_json_array`, etc.
* See https://github.com/meltano/sdk/blob/97d97de313511be4c21b842bf2ba0283d4bf5c02/singer_sdk/mapper.py#L297-L307
