### ISSUE TITLE
feat: Support passing context to the pagination class initialization scope

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1520]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Some pagination schemes may required access to the sync context object.

The `RESTStream.get_new_paginator` method is already being called within `RESTStream.request_records`, which has access to the context object, so it'd be rather easy to update the signature of the former to support passing it.

https://github.com/meltano/sdk/blob/47290d0470a38a9e978b53a7436212c43b605f2d/singer_sdk/streams/rest.py#L354

**Comment by edgarrmondragon** [comment]
To accomplish this in a backwards compatible way we'd need to do something like

```python
try:
    paginator = self.get_new_paginator(context=context)
except TypeError:
    paginator = self.get_new_paginator()
```

An even better way to accomplish the purpose of this feature request would be to make the context accessible within any scope within the stream class:

```python
class Stream:
  @final
  def get_context():
    return self.__context

  def get_new_paginator(self):
    context = self.get_context()
    start_dt = self.get_starting_datetime(context)
    return MyPaginator(start_dt)
```

**Comment by edgarrmondragon** [comment]
Still relevant

**Comment by kinghuang** [comment]
I've just run into this myself. I'm implementing a parent-child stream, and need the context from the parent in order o create the paginator in the child.

**Comment by edgarrmondragon** [comment]
> I've just run into this myself. I'm implementing a parent-child stream, and need the context from the parent in order to create the paginator in the child.

PRs are welcome for this feature!

**Comment by edgarrmondragon** [comment]
Small enough and I found the time to address this: #2529
