### ISSUE TITLE
Ability to provide custom mapper for properties with `"writeOnly": True` or other 'confidential'/'private' property tags

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1537]
This feature would enable users to specify a standard rule for fields that are of a specific classification level. For instance, the user could add a rule to hash, nullify, or mask all fields with `writeOnly` flag, or with data classification of `'pii'`.

Related to, and pairs with:

- https://github.com/meltano/sdk/issues/1538

**Comment by edgarrmondragon** [comment]
Still relevant
