### ISSUE TITLE
feat: Compute target metrics

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1573]
### Feature scope

Targets

### Description

We have a few metrics computed for taps:

* Record counter
* Request counter
* Sync timer
* Request timer

It would be interesting to similarly generate some metrics for targets. A few that come to mind:

* Message counter (tagged by message type and stream at least)
* Sync timer
* Record counter

This would allow developers (and platforms like Meltano) to monitor and correlate tap and target metrics.

**Comment by tayloramurphy** [comment]
It would probably be good to do a record calculator for targets too. If users filter rows from a mapper having the counts on both sides is useful!

**Comment by edgarrmondragon** [comment]
Still relevant
