### ISSUE TITLE
Unclear error message for target test suite: `KeyError: 'test_array_data'`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1575]
In working on the target-duckdb port, ran into this error message output which was not clear.

Several tests fail with the same error:

```
KeyError: 'test_array_data'
```

**Comment by edgarrmondragon** [comment]
@aaronsteers did you install the pytest plugin in `conftest.py`?

https://sdk.meltano.com/en/latest/testing.html#example-usage
