### ISSUE TITLE
bug: cookiecutter tap template defaults to deprecated get_next_page_token

### ISSUE THREAD

**Issue by sebastianswms** [meltano/sdk#1622]
### Singer SDK Version

0.24.0

### Is this a regression?

- [ ] Yes

### Python Version

3.6 (deprecated)

### Bug scope

Taps (catalog, state, etc.)

### Operating System

Windows - WSL

### Description

Using the information on the [Getting Started](https://sdk.meltano.com/en/latest/dev_guide.html) page, I used the following code to generate a new tap template:
`cookiecutter https://github.com/meltano/sdk --directory="cookiecutter/tap-template"`
After following the prompts, the template was successfully generated. However, it still included a template for the [deprecated ](https://sdk.meltano.com/en/latest/guides/pagination-classes.html) `get_next_page_token` method instead of using `get_new_paginator`.

**Comment by edgarrmondragon** [comment]
Thanks for reporting @sebastianswms!

We can indeed replace `get_next_page_token` with `get_new_paginator` in the template.

Labelled https://github.com/meltano/sdk/labels/Accepting%20Pull%20Requests in case anyone would like to take a stab at it.
