### ISSUE TITLE
bug: increment state is breaking when new_value is null

### ISSUE THREAD

**Issue by drbjim** [meltano/sdk#1714]
### Singer SDK Version

0.27.0

### Is this a regression?

- [ ] Yes

### Python Version

3.8

### Bug scope

Taps (catalog, state, etc.)

### Operating System

Linux-debian??

### Description

context - state is not present from backend and tap is trying full-refresh with configuration which has incremental key.

incremental state is breaking when new value is null.
so we need to check it's value if it is None or not.

https://github.com/meltano/sdk/blob/973f245d97e34efe6c2cf279998d88daaf4d43cf/singer_sdk/helpers/_state.py#LL217C7-L217C7

**Comment by edgarrmondragon** [comment]
Hopefully the fix is as simple as https://github.com/meltano/sdk/pull/2438?
