### ISSUE TITLE
bug: RECORD before SCHEMA message throws a KeyError, rather than an informative error

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1755]
### Singer SDK Version

0.28.0

### Is this a regression?

- [ ] Yes

### Python Version

3.10

### Bug scope

Targets (data type handling, batching, SQL object generation, etc.)

### Operating System

MacOS

### Description

It would be helpful in debugging Taps if errors relating to contravention of the Singer Spec were raised in SDK-based Targets with informative error messages.

**Comment by kgpayne** [comment]
Similarly [this](https://github.com/meltano/sdk/blob/main/singer_sdk/io_base.py#L50) `Exception` relating to "line missing required keys" is less helpful than understanding a SCHEMA was sent without a `properties` key. Test case [here](https://github.com/meltano/sdk/blob/main/singer_sdk/testing/target_tests.py#L50).

**Comment by visch** [comment]
https://github.com/meltano/sdk/issues/1146 :)

**Comment by kgpayne** [comment]
Closed as duplicate of #1146 and #1147. Thanks @visch 👍
