### ISSUE TITLE
feat: define a maxLength limit for varchar at the connector level

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#1812]
Originally raised in slack https://meltano.slack.com/archives/C01TCRBBJD7/p1688652938423919

The meltanolabs target-snowflake was throwing an error because its accepting the max length `4294967295` from the schema message as the varchar length which is larger than what snowflake accepts `16777216`. It looks like currently we just pass that value through to sqlalchemy with no validation to limit it from being too large and ultimately the DDL fails.

I'm going to fix it in target-snowflake but it does feel like something that should be handled by the SDK because its going to be relevant for most ever target. If we had a property method that needed to be implemented or a default class property that could be overridden. Another thing that might be worth checking out is if the sqlalchemy dialect package could tell us this generically somehow.

**Comment by pnadolny13** [comment]
This was solved in target-snowflake in https://github.com/MeltanoLabs/target-snowflake/pull/68. That has some logic specific to target-snowflake so using something like Edgar suggested in https://github.com/MeltanoLabs/target-snowflake/pull/68#discussion_r1254674308 would probably be best for the SDK.

**Comment by edgarrmondragon** [comment]
We'll be able to do this once https://github.com/meltano/sdk/pull/2618 is in

**Comment by BuzzCutNorman** [comment]
One thing I have run into with SQL Server is that Primary Keys and Foreign Keys of a table cannot be larger that 900 bytes.  Which means you really have two max length checks.  

The other thing I would point out is JSONSchema validates on character length while SQL Server is validating on size in bytes.  Here is link to Microsoft's remark about byte size vs character length.  https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16#remarks

**Comment by edgarrmondragon** [comment]
This will be made easier IMHO after https://github.com/meltano/sdk/pull/2732 lands, and this is still planned for 0.43.0
