### ISSUE TITLE
bug: incorrectly raising `MissingKeyPropertiesError` when column name conformed

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#1819]
### Singer SDK Version

0.29.0

### Is this a regression?

- [X] Yes

### Python Version

3.9

### Bug scope

Taps (catalog, state, etc.)

### Operating System

Mac OS

### Description

I noticed when migrated from 0.28.0 to 0.29.0 in target-snowflake https://github.com/MeltanoLabs/target-snowflake/pull/73 that some tests that previously passed are now failing because key properties arent found `singer_sdk.exceptions.MissingKeyPropertiesError: Record is missing one or more key_properties.`.

The issue is that [key_properties](https://github.com/meltano/sdk/blob/5bc4c57ada052a1b020670f32eb70db96a43cb5b/singer_sdk/sinks/sql.py#L254) is a list of conformed column names and the validation logic is reading the [raw record keys](https://github.com/meltano/sdk/blob/5bc4c57ada052a1b020670f32eb70db96a43cb5b/singer_sdk/sinks/core.py#L334) that are unconformed.

Solutions:

We should either conform the record column names before comparing in the `_singer_validate_message` method or not conform key properties in the property method. I chose the former for target-snowflake because I dont know the implications of altering the key_properties behavior.

### Code

```python
def _singer_validate_message(self, record: dict) -> None:
        """Ensure record conforms to Singer Spec.

        Args:
            record: Record (after parsing, schema validations and transformations).

        Raises:
            MissingKeyPropertiesError: If record is missing one or more key properties.
        """
        conformed_record_keys = [self.conform_name(key, "column") for key in record.keys()]
        if not all(key_property in conformed_record_keys for key_property in self.key_properties):
            msg = (
                f"Record is missing one or more key_properties. \n"
                f"Key Properties: {self.key_properties}, "
                f"Record Keys: {list(record.keys())}"
            )
            raise Exception(
                msg,
            )
```

**Comment by BuzzCutNorman** [comment]
@pnadolny13 I ran into this as well and found this as another way to resolve the issue.  Since `preprocess_record` occurs before `_singer_validate_message` in `_process_record_message` you can change the return of `preprocess_record` to `self.conform_record(record)`.  I think this would also remove the need for running `conform_records` in the `bulk_insert_records`

cc @edgarrmondragon

**Comment by edgarrmondragon** [comment]
@pnadolny13 @BuzzCutNorman I got a simple fix in https://github.com/meltano/sdk/pull/1853. Let me know if that works for you and looks right 🙂
