### ISSUE TITLE
feat(targets): Support loading records into a single column/field in the target

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1883]
### Feature scope

Targets (data type handling, batching, SQL object generation, tests, etc.)

### Description

Some targets in the wild already support a version of this. In particular, this is what [target-bigquery](https://github.com/z3z1ma/target-bigquery/blob/faddcfc12be9e1929cdd4816869e229c56431dff/README.md) has to say:

> It is the most versatile target for BigQuery. Extremely performant, resource efficient, and fast in all configurations enabling 20 different ingestion patterns. Denormalized variants indicate data is unpacked during load with a resultant schema in BigQuery based on the tap schema. Non-denormalized means we have a fixed schema which loads all data into an unstructured `JSON` column. They are both useful patterns. The latter allowing BigQuery to work with schemaless or rapidly changing sources such as MongoDB instantly, while the former is more performant and convenient to start modeling quickly.

## Current support

This is _almost_ supported by stream maps at the moment of writing. Consider the _countries_ sample in the SDK repo and the following stream maps configuration:

```json
{
    "stream_maps": {
        "countries": {
            "_data": "record",
            "__key_properties__": [],
            "__else__": null
        }
    },
    "stream_map_config": {}
}
```

Then run

```shell
poetry run python samples/sample_tap_countries --config stream_maps.json > mapped_countries.singer.jsonl
```

which contains in the following messages

* SCHEMA message

  ```json
  {
    "type": "SCHEMA",
    "stream": "countries",
    "schema": {
      "type": "object",
      "properties": {
        "_data": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "key_properties": [],
    "bookmark_properties": []
  }
  ```

* RECORD message

  ```json
  {
    "type": "RECORD",
    "stream": "countries",
    "record": {
      "_data": {
        "code": "AD",
        "name": "Andorra",
        "native": "Andorra",
        "phone": "376",
        "continent": {
          "code": "EU",
          "name": "Europe"
        },
        "capital": "Andorra la Vella",
        "currency": "EUR",
        "languages": [
          {
            "code": "ca",
            "name": "Catalan"
          }
        ],
        "emoji": "\ud83c\udde6\ud83c\udde9"
      }
    },
    "time_extracted": "2023-07-28T20:03:49.448913+00:00"
  }
  ```

### Needed improvements

* Note that in the above SCHEMA message, the `_data` field is of type `string`. This is because `record` is not recognized as a special name and the type inference logic falls back to the default string type: https://github.com/meltano/sdk/blob/759c77beb764be49b9a207635349b6d8ed420290/singer_sdk/mapper.py#L370-L384

  This is relatively easy to address: https://github.com/meltano/sdk/issues/1882

* There isn't a way to apply the mapping to all streams. Would be helped by https://github.com/meltano/sdk/issues/699

## Feature request

With this stream maps example as reference, it's a bit unclear what we need to do (in addition to addressing the improvements above). I can think of two options, not exclusive:

* Better stream maps documentation
* A target-level configuration that bypasses stream maps

```[tasklist]
### Tasks
- [ ] https://github.com/meltano/sdk/issues/1882
- [ ] https://github.com/meltano/sdk/issues/699
```

**Comment by edgarrmondragon** [comment]
cc @tayloramurphy

**Comment by pnadolny13** [comment]
Related to https://github.com/meltano/sdk/issues/699 and https://github.com/meltano/sdk/issues/1350 and https://github.com/meltano/sdk/issues/1883 and https://github.com/meltano/sdk/pull/1888. This approach would probably require a way to use wild card selection to say "all streams should be mapped in this way".

**Comment by edgarrmondragon** [comment]
This is supported! See https://github.com/MeltanoLabs/meltano-map-transform/pull/255
