### ISSUE TITLE
feat: Option to disable schema validation in targets

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#1904]
The transferwise variant of [target-snowflake](https://github.com/transferwise/pipelinewise-target-snowflake) has a `validate_records` setting that is defaulted to false. In the SDK we automatically do validation and don't provide a way to turn it off. We've seen some people struggle to transition to the new meltanolabs target-snowflake because validation is failing, its likely correctly failing but the solution for users is to fix the tap which becomes too big of a barrier for them when switching.

```
(Default: False) Validate every single record message to the corresponding JSON schema.
This option is disabled by default and invalid RECORD messages will fail only at load time by Snowflake.
Enabling this option will detect invalid records earlier but could cause performance degradation.
```

cc @tayloramurphy @edgarrmondragon

**Comment by edgarrmondragon** [comment]
This was made a lot easier to implement by https://github.com/meltano/sdk/issues/2136 (currently only available in prerelease v0.35.0a2).

One could override [`Sink.validate_schema`](https://sdk.meltano.com/en/v0.35.0a2/classes/singer_sdk.Sink.html#singer_sdk.Sink.validate_schema) to read from config:

```python
class MySink(Sink):
  @property
  def validate_schema(self) -> bool:
    return config.get("validate_records", False)
```
