### ISSUE TITLE
bug: is_sorted should be true for SQLStream with replication keys

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#1950]
Not sure if this is a bug or a design decision but shouldn't `is_sorted` be set to true in the default SQLStream implementation if we're adding an order by clause https://github.com/meltano/sdk/blob/6ba151915155eecdba2a43dce37531d13d4ad725/singer_sdk/streams/sql.py#L192?

Currently it accepts the default of False.

@edgarrmondragon what do you think?

**Comment by edgarrmondragon** [comment]
@pnadolny13 Yes, thanks for raising an actual issue 😅! I gave this a shot in tap-postgres a while ago (https://github.com/MeltanoLabs/tap-postgres/pull/221) but doesn't seem to be as simple. We'd need to dive deeper.

**Comment by edgarrmondragon** [comment]
@pnadolny13 I have a PR for this: https://github.com/meltano/sdk/pull/1951. Let me know what you think.
