### ISSUE TITLE
bug: SQLTaps Null replication key handling

### ISSUE THREAD

**Issue by visch** [meltano/sdk#1953]
### Singer SDK Version

0.31.1

### Is this a regression?

- [ ] Yes

### Python Version

3.8

### Bug scope

Taps (catalog, state, etc.)

### Operating System

n/a

### Description

`TypeError: '>=' not supported between instances of 'NoneType' and 'str' - When saving state` Full issue here https://github.com/MeltanoLabs/tap-postgres/issues/203 . For replication keys that have nulls you can have some issues. We have a solution here that seems to be fairly generic with SQLAlchemy https://github.com/MeltanoLabs/tap-postgres/pull/233

**Comment by edgarrmondragon** [comment]
Thanks for logging @visch! Seems like a quick win.

**Comment by edgarrmondragon** [comment]
Closed by #2094
