### ISSUE TITLE
refactor: Parse dates with a more performant library than `python-dateutil`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#2046]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Pendulum seems to perform significantly better at parsing datetimes. Doing this would improve target performance by making record parsing faster.

```[tasklist]
### Tasks
- [ ] https://github.com/meltano/sdk/issues/2048
- [ ] https://github.com/meltano/sdk/pull/2065
```

**Comment by BuzzCutNorman** [comment]
@edgarrmondragon I was looking at `pendulum` alternatives.  What about [`backports.datetime_fromisoformat`](https://github.com/movermeyer/backports.datetime_fromisoformat).  I came across it via this `ciso8601` flow chart [Should I use ciso8601?](https://github.com/closeio/ciso8601/blob/master/why_ciso8601.md).

https://github.com/movermeyer/backports.datetime_fromisoformat
