### ISSUE TITLE
feat: make replication_key be auto-selected

### ISSUE THREAD

**Issue by vmesel** [meltano/sdk#2106]
### Feature scope

Taps (catalog, state, stream maps, tests, etc.)

### Description

Primary keys are always pre-selected on the stream, but this is not the same with replication keys.

**Comment by edgarrmondragon** [comment]
Hi @vmesel!

Is this different from https://github.com/meltano/sdk/pull/1283 (shipped with [v0.18.0](https://github.com/meltano/sdk/releases/tag/v0.18.0))?

**Comment by vmesel** [comment]
@edgarrmondragon whenever I run tap's discovery method, the catalog gives the inclusion automatic flag to the pk, but not for the replication key.

```
        {
          "breadcrumb": [
            "properties",
            "id"
          ],
          "metadata": {
            "inclusion": "automatic"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "created"
          ],
          "metadata": {
            "inclusion": "available"
          }
```

**Comment by edgarrmondragon** [comment]
@vmesel which tap is that? Maybe it's using an older version of the sdk?

**Comment by vmesel** [comment]
@edgarrmondragon which singer SDK version made this a default?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon which singer SDK version made this a default?

@vmesel That'd be [0.18.0](https://github.com/meltano/sdk/releases/tag/v0.18.0).

**Comment by vmesel** [comment]
@edgarrmondragon ok, i think this is the issue. I'm bumping it right now and closing the issue so I don't take your time. Thanks for the help!
