### ISSUE TITLE
bug: `No schema for record field` warning when using schema flattening and field is null

### ISSUE THREAD

**Issue by tobiascadee** [meltano/sdk#2178]
### Singer SDK Version

0.34.1

### Is this a regression?

- [ ] Yes

### Python Version

3.10

### Bug scope

Mapping (stream maps, flattening, etc.)

### Operating System

MacOS

### Description

When using schema flattening option, getting a lot of `No schema for record field <field name>` warnings if a property of `ObjectType` is null. This should not trigger this warning as it could be that the whole object does not return values for a given record.

**Comment by edgarrmondragon** [comment]
Hi @tobiascadee!

This warning is logged in an SDK-based target when a field is present in a record, but not in the schema:

https://github.com/meltano/sdk/blob/47609ebe3b995dc92e6c48c6f995005414603fcd/singer_sdk/sinks/core.py#L490-L493

Did you enable flattening for

* the tap
* or the target
* or using the mapper plugin?

It'd also help to have the record and schema messages that are triggering this. For example, I tried to reproduce this with the countries sample in this repo using this config:

```json
{
    "flattening_enabled": true,
    "flattening_max_depth": 5
}
```

and it correctly flattened both the record and schema without missing any fields:

```
poetry run python samples/sample_tap_countries/ --config countries.flatten.json | poetry run python samples/sample_target_csv --config target_csv.config.json
```

**Comment by tobiascadee** [comment]
hey! thanks for the reply. I am using schema flattening for the target as I am developing one at the moment. I will add a few files which show the records and schema with and without flattening enabled. this is the schema in the tap: https://github.com/TicketSwap/tap-intercom/blob/28dc4a2350cd1a770517b3e84a9bc6e4e05133d0/tap_intercom/streams.py#L32

**Comment by tobiascadee** [comment]
@edgarrmondragon  I think the issue arises when the `ObjectType` field in the record is empty and schema flattening is enabled. in this case when some records do have a value in this specific field it will be flattened but if it is null it is not flattened the original field name is passed through which is then not in the schema

**Comment by taeefnajib** [comment]
@tobiascadee Hi, we are facing the issue. How did you end up solving this issue? Do you mind sharing the solution?
