### ISSUE TITLE
Diference between handling activate_version messages between hard_delete true and false

### ISSUE THREAD

**Issue by vitoravancini** [meltano/sdk#2227]
Hello everyone,

It seems that with hard_delete = true when we receive an activate_version message we delete everything equal or lesser than the new version:
https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/sinks/sql.py#L407

and when we set hard_delete = false we soft delete everything less than the new version:  
https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/connectors/sql.py#L1214

Is this how it supposed to be? 
When using target_snowflake(based on singer_sdk) with tap mssql we drop everything but the last batch at the end of the execution when hard_delete = true. 
The tap emits another activate_message at the end with the same version, which triggers a sql like 

```
delete from {table} where _sdc_record_version <= {version}
```

that {version} beeing the same version of all the records inserted up to that point.

Should we make both logics(hard_delete true and false) the same?

thank you!

**Comment by edgarrmondragon** [comment]
Should we make both logics(hard_delete true and false) the same?

@vitoravancini I think we should :)

PRs welcome!

**Comment by vitoravancini** [comment]
Nice, will try to send it later today
