### ISSUE TITLE
bug: `get_selected_schema` with selected sub-properties

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/sdk#2687]
### Singer SDK Version

0.39.1

### Is this a regression?

- [ ] Yes

### Python Version

3.8

### Bug scope

Taps (catalog, state, etc.)

### Operating System

Ubuntu 22.04

### Description

Given a `meltano.yml` with the following select rules

```yml
    select:
    - geo.*
```

calling `get_selected_schema` from the tap returns a schema with empty `properties`

```py
{'properties': {}, 'type': 'object'}
```

whereas with these rules

```yml
    select:
    - geo
    - geo.*
```

all properties of `geo` are present

```py
{'properties': {'geo': {'properties': {'city': {'type': ['string', 'null']}, 'country': {'type': ['string', 'null']}, 'continent': {'type': ['string', 'null']}, 'region': {'type': ['string', 'null']}, 'sub_continent': {'type': ['string', 'null']}, 'metro': {'type': ['string', 'null']}}, 'type': ['object', 'null']}}, 'type': 'object'}
```

For the first example, I expected all sub-properties of `geo` to be present (as in the second example). Is this a bug, or expected behaviour?

**Comment by edgarrmondragon** [comment]
Hey @ReubenFrankel! What does the raw catalog look like for this tap? That is, the output of `--discover`?

**Comment by ReubenFrankel** [comment]
With

```yml
    select:
    - geo.*
```

`meltano invoke --dump catalog tap-bigquery > catalog.json` gives

```json
        {
          "breadcrumb": [
            "properties",
            "geo"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": false
          }
        },
        {
          "breadcrumb": [
            "properties",
            "geo",
            "properties",
            "city"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
```

and with

```yml
    select:
    - geo
    - geo.*
```

`meltano invoke --dump catalog tap-bigquery > catalog.json` gives

```json
        {
          "breadcrumb": [
            "properties",
            "geo"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "geo",
            "properties",
            "city"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
```

I am providing `catalog.json` via `--catalog`.

**Comment by edgarrmondragon** [comment]
Thanks for sharing that @ReubenFrankel. So, FWIW I believe the SDK is doing the right thing here: since `geo` is not not selected, then it's dropped from the schema

That means Meltano's application of selection rules is at fault, and that `geo.*` should imply that `geo` is selected.

Otherwise, the SDK could avoid dropping `object` fields (and incur a small performance hit) to give you something like:

```
{'properties': {'geo': {'properties': {}, 'type': 'object'}}}
```

which I don't think is what you expect either?

(see aba2f5683106b07df652c5cb4f1350d8f5db515a for that)

PS: 2 years ago me should've created a bug report for this https://gitlab.com/meltano/sdk/-/issues/285#note_750983833.

**Comment by ReubenFrankel** [comment]
Yeah, I can see how that makes sense. I wondered whether the SDK would be doing something intelligent to handle that kind of situation, but it's probably best to take the catalog at face value here and just fix how it is generated on Meltano's side. 

> which I don't think is what you expect either?

Indeed. I'll have a look through Meltano issues and see if I can find one related to this? Otherwise I'll create a new one. Thanks!
