### ISSUE TITLE
bug: UUID incremental replication keys cannot be compared with UUID-strings coming from the state

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#2754]
### Singer SDK Version

0.41.0

### Is this a regression?

- [ ] Yes

### Python Version

NA

### Bug scope

Taps (catalog, state, etc.)

### Operating System

NA

### Description

When a SQL tap defines a UUID column as a replication key, the step where the value coming from the record and the value coming from the state dictionary are compared to increment the bookmark crashes because the `>=` operation is not supported between a `uuid.UUID`[^1] instance and a string.

We can fix by simply adding a branch to

https://github.com/meltano/sdk/blob/ae7516b8a16d625c05258570c74e242f1cf64e88/singer_sdk/helpers/_typing.py#L40-L45

that checks for an instance of `uuid.UUID` and returns the stringified value. The resulting string-to-string comparison should be safe down to the millisecond.

> [!NOTE]
> This may be only be an issue in a very narrow set of use cases, in particular where the experimental sortable UUID Version 7[^2] is enabled via database extensions, such as `pg_uuidv7`[^3].

Related:

- https://github.com/MeltanoLabs/tap-postgres/issues/519
- https://github.com/meltano/sdk/issues/2753

[^1]: https://docs.python.org/3/library/uuid.html#uuid.UUID
[^2]: https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#name-uuid-version-7
[^3]: https://github.com/craigpastro/pg_uuidv7

**Comment by edgarrmondragon** [comment]
Added this to the `v0.42` milestone to indicate that we could backport it to a `v0.42.1` if we get around to this quickly.

**Comment by edgarrmondragon** [comment]
@nikzavada in particular let me know if this

> The resulting string-to-string comparison should be safe down to the millisecond.

is accurate or if there's a risk of losing data by incrementing state when the underlying timestamp hasn't really moved.

**Comment by nikzavada** [comment]
@edgarrmondragon as we use the `>=` operator we should be safe even when the timestamp stays the same. The string-to-string comparison feels like a good solution here.

Thank you!

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/2755
