### ISSUE TITLE
feat: Add SHA256 encryption method

### ISSUE THREAD

**Issue by ben-schulz-mh** [meltano/sdk#2818]
### Feature scope

Inline mapping (stream maps, flattening, etc.)

### Description

Currently only MD5 is supported. SHA256 is a more secure encryption method that is used widely and is desired. For context, another ETL provider (Fivetran) use SHA256 and this would allow feature parity with that solution.

**Comment by edgarrmondragon** [comment]
PRs welcome @ben-schulz-mh!
