### ISSUE TITLE
Migrate GitLab CI publish jobs to GitHub Actions

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#681]
https://github.com/meltano/sdk/blob/050f604a190866fb16cc2fd1c5697d56010f0216/.gitlab-ci.yml#L131-L171

**Comment by aaronsteers** [comment]
@edgarrmondragon - Do you think the existing flows will get us through next week or do we need to tackle this sooner?

**Comment by edgarrmondragon** [comment]
@aaronsteers I would like at least test & lint pipelines to be working this week, and it seems those would be OK with the gh->gl CI approach.

The publishing and release pipelines are not as urgent.
