### ISSUE TITLE
ReadTheDocs builds are not being triggered

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#688]
Seems to be a permissions issue in the GitHub integration:

> Webhook activation failed. Make sure you have the necessary permissions.

**Comment by aaronsteers** [comment]
I've added the Githook to the GitHub project following these instructions: https://docs.readthedocs.io/en/stable/integrations.html

**Comment by aaronsteers** [comment]
Appears to be working now on new PR #689 

https://readthedocs.org/projects/meltano-sdk/builds/

<img width="842" alt="image" src="https://user-images.githubusercontent.com/18150651/171561840-3d1d6bea-5bd8-48bb-9e64-3f5d1bcd190a.png">

**Comment by aaronsteers** [comment]
Confirmed it appears deploys are working well now: #689 is merged and the content arrived successfully at sdk.meltano.com
