### ISSUE TITLE
Add docs for `flattening_enabled` and `flattening_max_depth`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#717]
I searched the docs and couldn't find any explanation of the flattening feature. We should add something, either under the stream maps docs page, or on another page.

https://github.com/meltano/sdk/blob/3998ac14918b6b2338851b8bb428485a9378ff49/singer_sdk/helpers/capabilities.py#L29-L43

Was discovered here:

- https://github.com/MeltanoLabs/meltano-map-transform/issues/24

**Comment by edgarrmondragon** [comment]
Still relevant
