### ISSUE TITLE
Project Samples link to Hub

### ISSUE THREAD

**Issue by visch** [meltano/sdk#728]
https://sdk.meltano.com/en/latest/code_samples.html#project-samples

Currently lists a static list of projects written with the SDK. Worked great, now there's so many more taps that have been written that aren't on the SDK. It'd be awesome to say something like

Click here for a list of ALL of the taps listed on the hub written by the sdk https://hub.meltano.com/extractors/tap-clickup  has a checkbox for "Written with the SDK" so it's probably not crazy to write an endpoint for this on the hub? (seperate issue on the hub repo needed?)

It'd also be nice if it was rendered as a table with last updated at, and ideally SDK version (but that's asking a little much?)

**Comment by edgarrmondragon** [comment]
Still relevant but blocked by https://github.com/meltano/hub/issues/951
