### ISSUE TITLE
Contributor docs for remote githooks service

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#741]
@edgarrmondragon - Do you mind adding a few sentences in the contributor docs regarding the recent addition of the 3rd party githooks services?

Thanks!

Re: #739, #12 

- https://github.com/meltano/sdk/pull/707

**Comment by edgarrmondragon** [comment]
@aaronsteers I see we have two contributing documents:

- [./CONTRIBUTING.md](https://github.com/meltano/sdk/blob/df2790b41725cbb3d9422b81b6696884e6b5ebee/CONTRIBUTING.md)
- [./docs/CONTRIBUTING.md](https://github.com/meltano/sdk/blob/df2790b41725cbb3d9422b81b6696884e6b5ebee/docs/CONTRIBUTING.md)

It's possible to include markdown docs from the project root in the sphinx docs: https://myst-parser.readthedocs.io/en/v0.16.0/sphinx/use.html#include-a-file-from-outside-the-docs-folder-like-readme-md.

Should we have the single `CONTRIBUTING.md` and add just _include_ it in the rtd docs?

**Comment by aaronsteers** [comment]
@edgarrmondragon - Oh man. Yeah, thanks for calling this out. I think a single `CONTRIBUTING.md` would be preferable - and probably nesting that into the `docs/` (rtd) directory would make the most sense - perhaps with a cross-link in the root `README.md` just to make sure it is discoverable...

What do you think?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon - Oh man. Yeah, thanks for calling this out. I think a single `CONTRIBUTING.md` would be preferable - and probably nesting that into the `docs/` (rtd) directory would make the most sense - perhaps with a cross-link in the root `README.md` just to make sure it is discoverable...
> 
> What do you think?

That sounded good. The contributing page in sdk.meltano.com is already linked in the readme 🙂. Here's the PR with these changes: https://github.com/meltano/sdk/pull/745.

**Comment by aaronsteers** [comment]
Note to self (@aaronsteers)
