### ISSUE TITLE
feature: Validate tap/target config options

### ISSUE THREAD

**Issue by laurentS** [meltano/sdk#753]
I just found that I've been running a tap with a misnamed option in the config file for almost 3 months. Despite this fact, `name=tap-github level=INFO message=Config validation passed with 0 warnings.`
It would be helpful if the sdk, as part of the config validation, actually raised an error when encountering unexpected options. For instance, `mypy` has an [option](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unused-configs) for this, which is very helpful to catch typos in config and such.

The following test clarifies the bug (inserted in `tests/core/test_plugin_config.py`):

```python
SAMPLE_CONFIG_WITH_ADDITIONAL_OPTION: Dict[str, Any] = {
    "default_true": False,
    "option_not_in_schema": 1,
}
def test_tap_config_validation_fails_on_invalid_option():
    """Verify that config validation fails on invalid option."""
    with pytest.raises(ValidationError):
        TapConfigTest(
            config=SAMPLE_CONFIG_WITH_ADDITIONAL_OPTION, parse_env_config=True
        )
    # this test fails because ValidationError is not raised
```

**Comment by edgarrmondragon** [comment]
@laurentS perhaps enabling a boolean `additionalProperties` to be used in the config schema might be sufficient? We already support the argument in [`ObjectType` and `PropertiesList`](https://sdk.meltano.com/en/latest/typing.html#singer_sdk.typing.ObjectType), so perhaps allowing a boolean to be used is enough for simple validation:

```
singer_sdk.exceptions.ConfigValidationError: Config validation failed: Additional properties are not allowed ('not_valid' was unexpected)
```

Wdyt?

**Comment by tayloramurphy** [comment]
FYI @edgarrmondragon unassigning you

**Comment by edgarrmondragon** [comment]
Developers can control this with `additional_properties=False` in their `PropertiesList`.
