### ISSUE TITLE
Unclear documentation - backoff_max_tries

### ISSUE THREAD

**Issue by kalyanr23** [meltano/sdk#784]
https://sdk.meltano.com/en/latest/classes/singer_sdk.RESTStream.html#singer_sdk.RESTStream.backoff_max_tries

Here, annotations show that the method should return int. But, description says, it can be set to `None` for retrying indefinitely. 
Can it be updated to include None in the return types or maybe use a -1 for indefinite retries?

**Comment by edgarrmondragon** [comment]
Hi @kalyanr23!

Thanks for reporting. You're right that it's nullable, and in fact it can also be a callable. The library uses the type annotation [`Optional[_MaybeCallable[int]]`](https://github.com/litl/backoff/blob/92e7b6e910accee30118a6f3d2cef4c62caa38f5/backoff/_decorator.py#L126), where `_MaybeCallable` is a generic wrapper: https://github.com/litl/backoff/blob/92e7b6e910accee30118a6f3d2cef4c62caa38f5/backoff/_typing.py#L39

I think we can do a similar thing, and maybe even for the other parameters too. Would you be willing to submit a PR?

**Comment by kalyanr23** [comment]
Sure. i'll submit a PR

**Comment by edgarrmondragon** [comment]
that's great @kalyanr23, thanks!

**Comment by edgarrmondragon** [comment]
This is being tackled by @rawwar on #868 🙂
