### ISSUE TITLE
`conform_record_data_types` is not recursive

### ISSUE THREAD

**Issue by Jack-Burnett** [meltano/sdk#800]
_typing.py has the function `conform_record_data_types`.
But it only iterates over the top level properties of the object, not any nested properties.

This has two negative consequences;
- Types are not normalised for nested values (For example, I am outputting lists of objects with dates on, and those dates are not normalised to strings by the sdk. This causes an error when it later tries to convert them to json).
- The check that a property exists in the schema would not be performed for any nested fields either

**Comment by edgarrmondragon** [comment]
Hi @Jack-Burnett, thanks for reporting. I agree, and it's probably a bug since it's unexpected behavior. PRs are welcome 😄

**Comment by Jack-Burnett** [comment]
Great, I'll see if I can cleanup the fix I used in my tap and submit it as a PR (probably won't be for a couple weeks at least though).

**Comment by edgarrmondragon** [comment]
@Jack-Burnett No worries, and thanks!
