### ISSUE TITLE
target cookie cutter SQL option doesn't use SQL

### ISSUE THREAD

**Issue by visch** [meltano/sdk#815]
1. `cookiecutter https://github.com/meltano/sdk --directory="cookiecutter/target-template"`
2. cat sinks.py

```python
# sinks.py
"""testermctestface target sink class, which handles writing streams."""


from singer_sdk.sinks import RecordSink


class testermctestfaceSink(RecordSink):
    """testermctestface target sink class."""

    def process_record(self, record: dict, context: dict) -> None:
        """Process the record."""
        # Sample:
        # ------
        # client.write(record)
```

**Comment by edgarrmondragon** [comment]
thanks for reporting @visch!

**Comment by edgarrmondragon** [comment]
@visch I went ahead and created https://github.com/meltano/sdk/pull/816 since this seems rather critical for folks to start building more targets with the SDK. Let me know if you think it's missing something 🙂
