### ISSUE TITLE
Cookie Cutter flake8-docstrings instead of pydocstyle

### ISSUE THREAD

**Issue by visch** [meltano/sdk#825]
`tox.ini` has a check for `poetry run pydocstyle target_postgres` in both the tap and target cookie cutters.

We could replace that with `flake8-docstrings` as that's how the sdk and meltano handle it. 🤷  took me away from coding a bit today as I"m trying to understand `pydocstyle` and saw this

**Comment by edgarrmondragon** [comment]
Closing in favor of https://github.com/meltano/sdk/issues/1596
