### ISSUE TITLE
[Bug]: cookiecutter tap SQL

### ISSUE THREAD

**Issue by visch** [meltano/sdk#866]
### Singer SDK Version

Latest

### Python Version

3.8

### Bug scope

Other

### Operating System

Ubuntu

### Description

1. Create tap with cookie cutter
2. Select SQL as the type of tap
3. There's classes that need to be modified to compile. See https://github.com/MeltanoLabs/tap-postgres/tree/main/tap_postgres for an implementation that tweaked the cookiecutter to make things work properly (Sorry don't have time to dive into exact details for this issue right now)

**Comment by edgarrmondragon** [comment]
This should be addressed now, but do open a new issue if there's anything off with the SQL templates
