### ISSUE TITLE
refactor: Make `auth_headers` and `auth_params` simple attributes instead of decorated properties in the base class

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#925]
The properties already default to `{}`, so there's no need to do it here too. The properties themselves also seem redundant - why not just use the attributes `auth_headers` and `auth_params` directly, and change them into properties in the future if they need special handling?

```suggestion
        request.headers.update(self.auth_headers)
        request.params.update(self.auth_params)
```

_Originally posted by @WillDaSilva in https://github.com/meltano/sdk/pull/842#discussion_r953849506_

**Comment by edgarrmondragon** [comment]
Still relevant

**Comment by WillDaSilva** [comment]
It's odd that stalebot closes issues as completed, instead of as "not planned". @edgarrmondragon should this have been closed?
