### ISSUE TITLE
Consider refactoring external dependencies

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#928]
At this point we have rewritten much of the python libraries and in many cases have used alternative approaches such as new classes and metadata operations. We recently ran into a bug with a nested dependency, and a simple fix is to remove the reference to this library.

Related to:

- #208

**Comment by aaronsteers** [comment]
@tayloramurphy - We're still having some bugs/issues related to the datetime library. I've asked @edgarrmondragon to pick this up, timeboxed to a `4` within the timeline for Tap-Toberfest.

Does that sound okay?

**Comment by tayloramurphy** [comment]
@aaronsteers yep - sounds good cc @edgarrmondragon
