### ISSUE TITLE
docs: Create version upgrade and future deprecations guide

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#943]
Should we start a 'version upgrade guide' doc that would like this as a change developers should make when updating to the newer version of the SDK?

_Originally posted by @aaronsteers in https://github.com/meltano/sdk/pull/732#discussion_r900408291_

**Comment by tayloramurphy** [comment]
@edgarrmondragon gut says yes! And as we start building taps/targets on the SDK we'll be able to dogfood it as well 😄

**Comment by edgarrmondragon** [comment]
We do have https://sdk.meltano.com/en/v0.30.0/deprecation.html
