### ISSUE TITLE
[Feature]: Support for hateoas style next page tokens like nextLink 

### ISSUE THREAD

**Issue by visch** [meltano/sdk#951]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

A common next page pattern for APIs is something like 

https://howtodoinjava.com/spring5/hateoas/pagination-links/#:~:text=%22href%22%3A%20%22http%3A//localhost%3A8080/api/albums%2Dlist%3Fpage%3D2%26size%3D2%26sort%3Dtitle%2Cdesc%22

Where the body looks like

```
{ 
    "_links": {
        "first": {
            "href": "http://localhost:8080/api/albums-list?page=0&size=2&sort=title,desc"
        },
        "prev": {
            "href": "http://localhost:8080/api/albums-list?page=0&size=2&sort=title,desc"
        },
        "self": {
            "href": "http://localhost:8080/api/albums-list?page=1&size=2&sort=title,desc"
        },
        "next": {
            "href": "http://localhost:8080/api/albums-list?page=2&size=2&sort=title,desc"
        },
        "last": {
            "href": "http://localhost:8080/api/albums-list?page=4&size=2&sort=title,desc"
        }
    }
}
```

The key here is that the `next` key is the **entire url**. Most APIs highly recommend in their documentation to use the entire url, not to just parse the next token out of the URL.  

Example API(s):

1. https://docs.microsoft.com/en-us/graph/paging#:~:text=Important%3A%20You,a%20different%20request.

Today the recommended implementation pattern for the SDK is to parse the link for the "nextpage" token. We should offer a method of overriding the entire URL. Maybe as a different `type` of `nextPage` implementation. Type would be `default` and we could have one be `hateoas_style`. 

Today to implement this "correctly" we have to override `prepare_request()`

Other references:

-  https://github.com/meltano/sdk/issues/359
 - https://github.com/meltano/sdk/issues/765 -> https://github.com/s7clarke10/tap-rest-api-msdk/tree/feature/support_link_list_pagination_tokens#additional-response-styles specefically the `hateoas_body` portion

**Comment by edgarrmondragon** [comment]
The [`BaseHATEOASPaginator`](https://sdk.meltano.com/en/latest/classes/singer_sdk.pagination.BaseHATEOASPaginator.html) tries to do that. For [example](https://github.com/meltano/sdk/blob/41b00cc7d80b7e3799f888f800ef0614e4c7758f/tests/core/rest/test_pagination.py#L297):

```python
class _CustomHATEOASPaginator(BaseHATEOASPaginator):
    def get_next_url(self, response: Response) -> str | None:
        """Get a parsed HATEOAS link for the next, if the response has one."""

        try:
            return first(
                extract_jsonpath("$.links[?(@.rel=='next')].href",
               response.json()),
            )
        except StopIteration:
            return None
```

In this case, the "next page token" that's passed around to the stream method is a [`ParseResult`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.ParseResult) tuple.

That said, I'd be a bit wary of hardcoding a "hateoas" style when APIs all do what as they please with the standard 😅.

Perhaps it'd be the job of the "paginator" (should it be called "pager"? 🤔) to generate requests?

What Scrapy does comes to mind, where it "yields" requests that are then processed into the appropriate responses:

```python
class QuotesSpider(scrapy.Spider):
    name = 'quotes'
    start_urls = [
        'https://quotes.toscrape.com/tag/humor/',
    ]

    def parse(self, response):
        for quote in response.css('div.quote'):
            yield {
                'author': quote.xpath('span/small/text()').get(),
                'text': quote.css('span.text::text').get(),
            }

        next_page = response.css('li.next a::attr("href")').get()
        if next_page is not None:
            yield response.follow(next_page, self.parse)
```

`Response.follow` returns a `Request` object, but it could also be constructed from scratch with any URL, headers, etc.

**Comment by visch** [comment]
> The [`BaseHATEOASPaginator`](https://sdk.meltano.com/en/latest/classes/singer_sdk.pagination.BaseHATEOASPaginator.html) tries to do that. For [example](https://github.com/meltano/sdk/blob/41b00cc7d80b7e3799f888f800ef0614e4c7758f/tests/core/rest/test_pagination.py#L297):
> 
> ```python
> class _CustomHATEOASPaginator(BaseHATEOASPaginator):
>     def get_next_url(self, response: Response) -> str | None:
>         """Get a parsed HATEOAS link for the next, if the response has one."""
> 
>         try:
>             return first(
>                 extract_jsonpath("$.links[?(@.rel=='next')].href",
>                response.json()),
>             )
>         except StopIteration:
>             return None
> ```
> 
> In this case, the "next page token" that's passed around to the stream method is a [`ParseResult`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.ParseResult) tuple.
> 
> That said, I'd be a bit wary of hardcoding a "hateoas" style when APIs all do what as they please with the standard 😅.
> 
> Perhaps it'd be the job of the "paginator" (should it be called "pager"? 🤔) to generate requests?
> 
> What Scrapy does comes to mind, where it "yields" requests that are then processed into the appropriate responses:
> 
> ```python
> class QuotesSpider(scrapy.Spider):
>     name = 'quotes'
>     start_urls = [
>         'https://quotes.toscrape.com/tag/humor/',
>     ]
> 
>     def parse(self, response):
>         for quote in response.css('div.quote'):
>             yield {
>                 'author': quote.xpath('span/small/text()').get(),
>                 'text': quote.css('span.text::text').get(),
>             }
> 
>         next_page = response.css('li.next a::attr("href")').get()
>         if next_page is not None:
>             yield response.follow(next_page, self.parse)
> ```
> 
> `Response.follow` returns a `Request` object, but it could also be constructed from scratch with any URL, headers, etc.

This was merged last week!!!! Meltano team is great, I need to update myself on the release notes. What are the odds I hit this at the same time that you merge this :O 

Thank you for the example as well, I'll give this a shot I'll assume it works if not I"ll reopen / create a seperate issue

**Comment by visch** [comment]
> The [`BaseHATEOASPaginator`](https://sdk.meltano.com/en/latest/classes/singer_sdk.pagination.BaseHATEOASPaginator.html) tries to do that. For [example](https://github.com/meltano/sdk/blob/41b00cc7d80b7e3799f888f800ef0614e4c7758f/tests/core/rest/test_pagination.py#L297):
> 
> ```python
> class _CustomHATEOASPaginator(BaseHATEOASPaginator):
>     def get_next_url(self, response: Response) -> str | None:
>         """Get a parsed HATEOAS link for the next, if the response has one."""
> 
>         try:
>             return first(
>                 extract_jsonpath("$.links[?(@.rel=='next')].href",
>                response.json()),
>             )
>         except StopIteration:
>             return None
> ```
> 
> In this case, the "next page token" that's passed around to the stream method is a [`ParseResult`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.ParseResult) tuple.
> 
> That said, I'd be a bit wary of hardcoding a "hateoas" style when APIs all do what as they please with the standard 😅.
> 
> Perhaps it'd be the job of the "paginator" (should it be called "pager"? 🤔) to generate requests?
> 
> What Scrapy does comes to mind, where it "yields" requests that are then processed into the appropriate responses:
> 
> ```python
> class QuotesSpider(scrapy.Spider):
>     name = 'quotes'
>     start_urls = [
>         'https://quotes.toscrape.com/tag/humor/',
>     ]
> 
>     def parse(self, response):
>         for quote in response.css('div.quote'):
>             yield {
>                 'author': quote.xpath('span/small/text()').get(),
>                 'text': quote.css('span.text::text').get(),
>             }
> 
>         next_page = response.css('li.next a::attr("href")').get()
>         if next_page is not None:
>             yield response.follow(next_page, self.parse)
> ```
> 
> `Response.follow` returns a `Request` object, but it could also be constructed from scratch with any URL, headers, etc.

Realized this feature isn't released yet, I'll try it another time I guess I don't want to build on an unreleased feature for this tap.
