### ISSUE TITLE
Improve docs left-nav organization

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#964]
The left-nav section of sdk.meltano.com is getting pretty cluttered.

Would be good to refactor into the 4-pronged section headers from the diataxis docs framework: https://diataxis.fr/

![image](https://user-images.githubusercontent.com/18150651/190054180-baef57ff-bbed-4f26-bc53-1e362eb0ad05.png)

Currently:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/18150651/190054304-b5fb4082-2956-4277-9419-a82c66d12949.png">

Possible reorg:

1. Guides
	  - [SDK Dev Guide](https://sdk.meltano.com/en/latest/dev_guide.html)
	  - [Contributing to the SDK](https://sdk.meltano.com/en/latest/CONTRIBUTING.html)
	  - [Singer Tap Porting Guide](https://sdk.meltano.com/en/latest/porting.html)
1. Tutorials
	  - [How to design a Sink](https://sdk.meltano.com/en/latest/sinks.html)
1. Explanation
	  - [Plugin Capabilities](https://sdk.meltano.com/en/latest/capabilities.html)
	  - [Inline Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html)
	  - [Parent-Child Streams](https://sdk.meltano.com/en/latest/parent_streams.html)
	  - [SDK Implementation Details](https://sdk.meltano.com/en/latest/implementation/index.html)
	  - [Stream Partitioning](https://sdk.meltano.com/en/latest/partitioning.html)
	  - [Frequently Asked Questions](https://sdk.meltano.com/en/latest/faq.html)
1. Reference
	  - [SDK Reference](https://sdk.meltano.com/en/latest/reference.html)
	  - [Python Tips for SDK Developers](https://sdk.meltano.com/en/latest/python_tips.html)
	  - [JSON Schema builder](https://sdk.meltano.com/en/latest/typing.html)
	  - [SDK Code Samples](https://sdk.meltano.com/en/latest/code_samples.html)
	  - [Command Line Samples](https://sdk.meltano.com/en/latest/cli_commands.html)

cc @cjohnhanson, @edgarrmondragon, @afolson, @sbalnojan

**Comment by edgarrmondragon** [comment]
Agreed! There's too much sprawl in that left-nav. Outside of `SDK Reference`, the other items can probably be grouped as (mostly) explanations and guides (Dev Guide, Code Samples).

**Comment by edgarrmondragon** [comment]
It's much better now: https://sdk.meltano.com/en/v0.30.0/
