### ISSUE TITLE
[Docs]: document debugger configuration for common IDEs

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#973]
### Feature scope

Other

### Description

As per [this comment](https://github.com/meltano/sdk/pull/968#issuecomment-1248347852), it might be beneficial to provide example debugger configuration for 1 or 2 more IDEs (in addition to vscode added in #968) as a precursor to adding config files (contingent on a new question) to the cookiecutter templates.

**Comment by edgarrmondragon** [comment]
We do have PyCharm docs now: https://sdk.meltano.com/en/v0.30.0/dev_guide.html#pycharm-debugging
