### ISSUE TITLE
feat: support stream property selection in SQL streams

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#974]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Currently, for SQL-type streams we do the equivalent of `select * from table` to retrieve records, and rely on the `pop_deselected_record_properties ` helper from the SDK to remove/pop any deselected properties before returning the final `RECORD`. This is OK in the general case, but does mean that we are retrieving more data than necessary, only to filter it locally. However, in the `BATCH` case, records are not processed locally at all, and therefore never have selection criteria applied. Therefore, to solve both requirements, we could add a `get_selected_properties` helper to return the column names of a given stream to be used when constructing the select statements for both `RECORD` and `BATCH` implementations of SQL-type streams.

**Comment by aaronsteers** [comment]
@kgpayne - It looks like the problematic code is here in `get_records()`:

https://github.com/meltano/sdk/blob/main/singer_sdk/streams/sql.py#L1045-L1046

```py
        table = self.connector.get_table(self.fully_qualified_name)
        query = table.select()
```

It looks like the `SQLConnector.get_table()` call could pass an explicit column list: https://docs.sqlalchemy.org/en/14/core/selectable.html#sqlalchemy.sql.expression.table

> Therefore, to solve both requirements, we could add a get_selected_properties helper to return the column names of a given stream...

Yeah. I think that's the right approach. Pseudocode like this perhaps?:

```py
        selected_column_names = self.get_selected_schema()["properties"].keys() 
        # or: selected_column_names = self.selected_schema["properties"].keys()
        table = self.connector.get_table(self.fully_qualified_name, column_names=selected_column_names)
        query = table.select()
```

**Comment by aaronsteers** [comment]
Rather than make this a blocker to `tap-snowflake`, what do you think of solving this via subclassing and overrides in `tap-snowflake`, then migrate what works into a PR here in SDK?
