### ISSUE TITLE
change: in stream maps, accept `'NULL'` (or similar) as an alias of `null` to suppress columns and streams

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#983]
As of today, Meltano does not preserve `null` nodes in plugin `config` blocks.

As a workaround, we could alter the SDK's parsing logic to _also_ accept `'NULL'` as instruction to remove / filter out the associated property or stream.

Related to:

- https://github.com/meltano/meltano/issues/6382#issuecomment-1233423611

**Comment by aaronsteers** [comment]
@edgarrmondragon - I just logged this as a short-term solve for the related meltano#6382. 

I scoped small, estimating as a `2`, but with the understanding that it could be a `4` if we run into surprises. Do you think that's about right?

**Comment by edgarrmondragon** [comment]
@aaronsteers Ok, so current mapper configs that accept null as a special value, different from "missing":

- `__else__: null` Remove all streams/fields except for those explicitly mapped
- `some_property: null` The stream property `some_property` will be excluded from output

And other configs will null == missing functionality:

- `__filter__`

I agree that this is a `2` assuming that's all there is to it.

**Comment by aaronsteers** [comment]
Thanks, @edgarrmondragon ! The only other thing that comes to mind is `some_stream_name: null` which functions just as with properties but at the stream level.

**Comment by aaronsteers** [comment]
Related:

- https://github.com/MeltanoLabs/meltano-map-transform/pull/63#discussion_r989486851

**Comment by visch** [comment]
https://github.com/meltano/meltano/issues/6382#issuecomment-1277619869 

fyi @edgarrmondragon  / @aaronsteers  maybe this works with mappers but not with extractors in meltano?

**Comment by edgarrmondragon** [comment]
> [meltano/meltano#6382 (comment)](https://github.com/meltano/meltano/issues/6382#issuecomment-1277619869)
> 
> fyi @edgarrmondragon / @aaronsteers maybe this works with mappers but not with extractors in meltano?

@visch I can confirm that's the case and left a comment in the suggested sample for https://github.com/meltano/sdk/issues/1073
