### ISSUE TITLE
[Bug]: Cookiecutter fails when running meltano install

### ISSUE THREAD

**Issue by visch** [meltano/sdk#992]
### Singer SDK Version

0.11.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Linux

### Description

When setting up a new Rest API tap with the cookie cutter if you run `meltano install` you'll receive `Environment 'dev' was not found.`  With the latest version of Meltano

**Comment by edgarrmondragon** [comment]
So, this is an easy fix. We simply need to add

```yaml
environments:
- name: dev
```

to the `meltano.yml` in the cookiecutter templates.

PRs are welcome, otherwise I'll pick this up tomorrow 🙂

**Comment by edgarrmondragon** [comment]
Addressed by https://github.com/meltano/sdk/pull/1093/files
