### ISSUE TITLE
Feat: Build (empty?) cookiecutters and run with Meltano to be sure they work

### ISSUE THREAD

**Issue by visch** [meltano/sdk#993]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Making sure cookiecutters continue to work is hard! It'd be great to build a cookiecutter project as a part of CI with the SDK to be sure the latest version of the cookiecutter with the latest version of meltano work!

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/sdk/pull/1410
