### ISSUE TITLE
[Feature]: When _LOG_REQUEST_METRIC_URLS = True , the url base should be included

### ISSUE THREAD

**Issue by visch** [meltano/sdk#996]
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Right now the metric url looks like this
```
INFO:tap-indeedsponsoredjobs:INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.14543, "tags": {"endpoint": "/appinfo", "http_status_code": 403, "status": "failed", "url": "/v2/api/appinfo?perPage=1000000000
  2 Traceback (most recent call last):
 ```
 
 In my case (and most of my cases) I'm not worried about leaking sensitive crednetials via the URL, and having the baseURL is helpful. I tend to override this in my taps during debugging and I forget about it until I write a new tap. The line I add is here https://github.com/meltano/sdk/blob/main/singer_sdk/streams/rest.py#L247 I add base_url to the extra tags. 
 
This use case comes up with lots of Rest APIS because you have a different base URL for authentication vs the "data" api you'll hit later. Another large subset is when there's a number of different "data" apis you need to hit.

**Comment by edgarrmondragon** [comment]
Full debug request logs can now be achieved with a [custom logging configuration](https://sdk.meltano.com/en/latest/implementation/logging.html#custom-logging-configuration):

```yaml
version: 1
disable_existing_loggers: false
loggers:
  urllib3:
    level: DEBUG
```

`urllib3.connectionpool` logs should be emitted with the above config:

```
2022-12-20 17:33:08,324 | DEBUG    | urllib3.connectionpool | Starting new HTTPS connection (1): api.jotform.com:443
2022-12-20 17:33:08,631 | DEBUG    | urllib3.connectionpool | https://api.jotform.com:443 "GET /user/forms?limit=100 HTTP/1.1" 200 None
```
