### ISSUE TITLE
[Bug]: Cookies not stored between Auth and Normal requests

### ISSUE THREAD

**Issue by visch** [meltano/sdk#997]
### Singer SDK Version

0.11.0

### Python Version

3.8

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

Ubuntu

### Description

This is probably a feature? Not sure 🤷  

Using the latest SDK version, I just hit a tap that fronts its requests with CloudFlare. CloudFlare really wants me to store the cookies that are sent back and keep them with each request (Specifically the Auth request gets cookies and I need to send these back with the normal data requests) 

Tieing the two request session together works pretty well to solve this

Error code 1020 with Cloud Flare.

**Comment by edgarrmondragon** [comment]
If the response contains the [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header for the relevant cookies, then it should be a matter of passing the same `requests.Session` instance.

@visch I assume this only affects the `OAuthAuthenticator`, right?

**Comment by visch** [comment]
> If the response contains the [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header for the relevant cookies, then it should be a matter of passing the same `requests.Session` instance.
> 
> @visch I assume this only affects the `OAuthAuthenticator`, right?

@edgarrmondragon  I don't know, but  I know that it impacted me when I was using the `OAuthAuthenticator` !

**Comment by visch** [comment]
@edgarrmondragon  if someone does fix this, we should also add the same User Agent to both requests this also stuck me up for a bit as CloudFlare was being extra picky

**Comment by edgarrmondragon** [comment]
> we should also add the same User Agent to both requests this also stuck me up for a bit as CloudFlare was being extra picky

@visch that makes sense. That might require making the distinction in the `RESTStream` API between _dynamic_ and _static_ headers, i.e. ones which change between requests and ones that remain the same throughout the session. The static headers would be passed to the authenticator, while the dynamic ones would be constructed for each request, with help from the authenticator (auth headers, etc.)

**Comment by visch** [comment]
> > we should also add the same User Agent to both requests this also stuck me up for a bit as CloudFlare was being extra picky
> 
> @visch that makes sense. That might require making the distinction in the `RESTStream` API between _dynamic_ and _static_ headers, i.e. ones which change between requests and ones that remain the same throughout the session. The static headers would be passed to the authenticator, while the dynamic ones would be constructed for each request, with help from the authenticator (auth headers, etc.)

hmm I was thinking just hard coding `User-Agent` and that's pretty much how it works in the RestStream right now but maybe I'm a bit too hacky here as there could be other reasons CloudFlare (or other random WAFs) could block you

**Comment by visch** [comment]
For what it's worth @edgarrmondragon  I just found out the tap I'm hitting this with was offloading x percent of traffic to cloudflare and there's an error on their side. For what it's worth this will probably be a non issue for me in a few days to weeks.

**Comment by visch** [comment]
To "beat" cloudflare https://github.com/venomous/cloudscraper ended up being the solution. Add a setter for requests.session and then pass that into `self.requests_session = cloudscrapper.create_scraper(self.requests_session)`

**Comment by edgarrmondragon** [comment]
@visch nice, so `CloudScraper` is a subclass of `requests.Session`. So maybe there's motivation to provide developers with hooks to override the session class and maybe help with https://github.com/meltano/sdk/issues/236 along the way.

**Comment by edgarrmondragon** [comment]
Still relevant and open to contributions

**Comment by edgarrmondragon** [comment]
Authenticators are `requests` auth callables[^1] so implementing one that preserves cookies should be as simple as creating a class with a constructor that takes in a `requests.cookies.RequestsCookieJar`:

```python
# auth.py
import requests

class MyAuth:
  def __init__(self, cookies):
    self.cookies = cookies

  def __call__(self, request):
    response = requests.post(..., cookies=self.cookies)
    # ... process response to update the request with auth headers, etc.
    return request

# client.py
from .auth import MyAuth

class MyStream(RESTStream):
  @property
  def authenticator(self):
    return MyAuth(cookies=self.requests_session.cookies)
```

Passing around the session itself for auth is probably not a good idea since it can lead to recursion errors where the auth request needs the auth callable...

[^1]: https://docs.python-requests.org/en/latest/user/authentication/#new-forms-of-authentication
